import {test} from 'node:test';import assert from 'node:assert/strict';import {EventEmitter} from 'node:events';import {readFileSync} from 'node:fs';
import {holdGameForAccount} from '../app/game/account-pause.mjs';
import {discoverAccountWallets,connectAccountWallet,signAccountMessage,watchAccountWallet} from '../app/game/account-wallets.mjs';
function gameFixture({scenePaused=false,manualPaused=false}={}){let paused=scenePaused;const s={sys:{settings:{key:'game'}},events:new EventEmitter(),run:{wave:3,score:9120},lives:2,paused:manualPaused,physics:{world:{isPaused:manualPaused,pause(){this.isPaused=true},resume(){this.isPaused=false}}},input:{enabled:!scenePaused,keyboard:{enabled:!scenePaused,resetKeys(){}}},clearTouchState(){this.cleared=true}};const game={input:{keyboard:{enabled:true}},events:new EventEmitter(),scene:{getScenes:()=>[s],isActive:()=>!paused,isPaused:()=>paused,pause:()=>paused=true,resume:()=>paused=false}};return {game,s,getPaused:()=>paused}}
test('account modal pauses game, physics and keyboard without altering flight',()=>{const {game,s,getPaused}=gameFixture(),run=s.run,release=holdGameForAccount(game);assert.equal(getPaused(),true);assert.equal(s.physics.world.isPaused,true);assert.equal(s.input.keyboard.enabled,false);assert.equal(game.input.keyboard.enabled,false);assert.equal(s.run,run);release();assert.equal(getPaused(),false);assert.equal(s.paused,false);assert.equal(s.run.score,9120);assert.equal(s.lives,2);assert.equal(s.input.keyboard.enabled,true);assert.equal(game.input.keyboard.enabled,true)});
test('closing sign-in does not resume an already-paused continue dialog',()=>{const {game,s,getPaused}=gameFixture({scenePaused:true,manualPaused:true});const release=holdGameForAccount(game);release();assert.equal(getPaused(),true);assert.equal(s.paused,true);assert.equal(s.input.enabled,false);assert.equal(s.physics.world.isPaused,true)});
test('manual Escape pause remains after sign-in closes',()=>{const {game,s,getPaused}=gameFixture({manualPaused:true});const release=holdGameForAccount(game);release();assert.equal(getPaused(),false);assert.equal(s.paused,true);assert.equal(s.physics.world.isPaused,true)});
test('shutdown while sign-in is open never restores stale state to a new flight',()=>{const {game,s}=gameFixture();const release=holdGameForAccount(game);s.events.emit('shutdown');s.run={wave:0,score:0};s.paused=false;release();assert.equal(s.run.score,0);assert.equal(s.paused,false);assert.equal(s.events.listenerCount('shutdown'),0)});
test('release is idempotent and removes poststep listener',()=>{const {game}=gameFixture();const release=holdGameForAccount(game);release();release();assert.equal(game.events.listenerCount('poststep'),0)});
function winFixture(){const win=new EventTarget();win.Event=Event;win.CustomEvent=CustomEvent;return win}
function suiFixture(){const account={address:'0x1',chains:['sui:mainnet']},events=new EventEmitter(),calls=[];const wallet={name:'Sui fixture',chains:['sui:mainnet'],accounts:[account],features:{'standard:connect':{connect:async()=>({accounts:wallet.accounts})},'standard:events':{on:(e,fn)=>{events.on(e,fn);return()=>events.off(e,fn)}},'sui:signPersonalMessage':{signPersonalMessage:async p=>{calls.push(p);return{signature:'signed'}}}}};return{wallet,account,calls,events}}
test('Wallet Standard providers are discovered before or after app startup and deduplicated',()=>{const win=winFixture(),{wallet}=suiFixture();win.addEventListener('wallet-standard:app-ready',e=>e.detail.register(wallet));const d=discoverAccountWallets(win);assert.equal(d.list('sui').length,1);win.dispatchEvent(new CustomEvent('wallet-standard:register-wallet',{detail:api=>api.register(wallet)}));assert.equal(d.list('sui').length,1);d.destroy()});
test('unsupported wallets and malformed announcements are ignored',()=>{const win=winFixture(),d=discoverAccountWallets(win);win.dispatchEvent(new CustomEvent('wallet-standard:register-wallet',{detail:()=>{throw Error()}}));win.dispatchEvent(new CustomEvent('wallet-standard:register-wallet',{detail:api=>api.register({name:'unsupported',features:{}})}));assert.equal(d.list('sui').length,0);d.destroy()});
test('EIP-6963 discovers multiple providers, including late announcements',()=>{const win=winFixture(),d=discoverAccountWallets(win),p1={request(){}},p2={request(){}};for(const p of [p1,p1,p2])win.dispatchEvent(new CustomEvent('eip6963:announceProvider',{detail:{info:{name:'EVM'},provider:p}}));assert.equal(d.list('evm').length,2);d.destroy()});
test('Sui signs exact message bytes with selected Mainnet account and no transaction',async()=>{const f=suiFixture(),c=await connectAccountWallet({family:'sui',provider:f.wallet});assert.equal(await signAccountMessage(c,f.account,'TREE sign in'),'signed');assert.equal(new TextDecoder().decode(f.calls[0].message),'TREE sign in');assert.equal(f.calls[0].chain,'sui:mainnet');assert.equal(f.calls[0].account,f.account)});
test('Sui account change detected before or after wallet signature',async()=>{const f=suiFixture(),c=await connectAccountWallet({family:'sui',provider:f.wallet});f.wallet.accounts=[];await assert.rejects(signAccountMessage(c,f.account,'Sign'),/changed/);assert.equal(f.calls.length,0)});
test('wallet listeners unsubscribe cleanly',async()=>{const f=suiFixture(),c=await connectAccountWallet({family:'sui',provider:f.wallet});let changed=0;const off=watchAccountWallet(c,()=>changed++);f.events.emit('change',{accounts:[]});off();f.events.emit('change',{accounts:[]});assert.equal(changed,1)});
test('EVM signs via personal_sign and never invokes transactions or token approvals',async()=>{let chain=97;const address='0x'+'2'.repeat(40),calls=[];const p={request:async q=>{calls.push(q);if(q.method==='eth_requestAccounts'||q.method==='eth_accounts')return[address];if(q.method==='eth_chainId')return '0x'+chain.toString(16);if(q.method==='wallet_switchEthereumChain'){chain=Number(q.params[0].chainId);return;}if(q.method==='personal_sign')return'signed';throw Error('Forbidden method '+q.method)}};const c=await connectAccountWallet({family:'evm',provider:p},46630);await signAccountMessage(c,c.accounts[0],'Sign');assert.equal(chain,46630);assert.equal(calls.at(-3).method,'personal_sign');assert.ok(calls.every(c=>!c.method.includes('send')&&!c.method.includes('Transaction')))});
test('client UI never opens or navigates another TREE page',()=>{const s=readFileSync(new URL('../app/game/tree-account.mjs',import.meta.url),'utf8');assert.doesNotMatch(s,/window\.open|location\.(assign|replace)|iframe|localStorage/);assert.match(s,/holdGameForAccount/);assert.match(s,/alive\(token\)/)});
