import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {createContinueAttempt,restoreArborwing,prepareArborwing,wireContinueGame} from '../app/game/continue-flow.mjs';
import {createCreditsProxy} from '../netlify/lib/canopy-credits-proxy.mjs';
const account='12345678-1234-4234-8234-123456789abc';
function mockApi(){let status='reserved',drop=null;const calls=[],seen=new Map();return {calls,setDrop:a=>drop=a,async api(c){calls.push(c);let result=seen.get(c.requestId);if(!result){if(c.action==='open-run')result={runId:'run'};else{if(c.action==='commit')status='committed';if(c.action==='deliver')status='delivered';if(c.action==='release'||c.action==='finish')status='released';result={reservationId:'res',status,lives:3};}seen.set(c.requestId,result);}if(drop===c.action){drop=null;throw Error('response lost');}return {result,ledger:{accountId:account,mode:'simulation'}};}};}
function attemptFixture(){const service=mockApi(),count={prepare:0,apply:0,boundary:0,resume:0};const attempt=createContinueAttempt({api:service.api,prepare(){count.prepare++;},apply(){count.apply++;},boundary(){count.boundary++;},resume(){count.resume++;}});return {service,count,attempt};}
test('successful continue reserves, commits and confirms before resuming once',async()=>{const f=attemptFixture();assert.equal(await f.attempt.continue(),true);await f.attempt.continue();assert.equal(f.count.apply,1);assert.equal(f.count.boundary,1);assert.equal(f.count.resume,1);assert.deepEqual(f.service.calls.map(c=>c.action),['open-run','reserve','commit','deliver']);});
test('double click cannot start two charge sequences',async()=>{const f=attemptFixture();await Promise.all([f.attempt.continue(),f.attempt.continue()]);assert.equal(f.service.calls.filter(c=>c.action==='reserve').length,1);assert.equal(f.count.resume,1);});
test('lost commit response is retried with identical ID before any restoration',async()=>{const f=attemptFixture();f.service.setDrop('commit');await assert.rejects(f.attempt.continue(),/response lost/);assert.equal(f.count.apply,0);await f.attempt.continue();const commits=f.service.calls.filter(c=>c.action==='commit');assert.deepEqual(commits[0],commits[1]);assert.equal(f.count.apply,1);});
test('lost delivery response does not restore lives or freeze records twice',async()=>{const f=attemptFixture();f.service.setDrop('deliver');await assert.rejects(f.attempt.continue(),/response lost/);assert.equal(f.count.resume,0);assert.equal(await f.attempt.cancel(),false);await f.attempt.continue();assert.equal(f.count.apply,1);assert.equal(f.count.boundary,1);assert.equal(f.count.resume,1);});
test('failed preparation releases credits and never applies a continue',async()=>{const f=attemptFixture();await assert.rejects(f.attempt.continue({failPreparation:true}),/Simulated game failure/);assert.equal(f.count.apply,0);assert.equal(f.count.boundary,0);assert.equal(f.service.calls.at(-1).action,'release');assert.equal(f.attempt.state.closed,true);});
test('application failure requests reversing release and never resumes',async()=>{const service=mockApi();let resumed=false;const a=createContinueAttempt({api:service.api,prepare(){},boundary(){},apply(){throw Error('game failure')},resume(){resumed=true;}});await assert.rejects(a.continue(),/game failure/);assert.equal(resumed,false);assert.equal(service.calls.at(-1).action,'release');});
test('declining before a purchase is free',async()=>{const f=attemptFixture();assert.equal(await f.attempt.cancel(),true);assert.equal(f.service.calls.length,0);assert.equal(await f.attempt.continue(),false);});
function sceneFixture(){const events=new EventEmitter(),object=()=>({active:true,destroy(){this.active=false},setData(){return this}});const player={body:{enable:false,reset(){}},setPosition(){return this},setVelocity(){return this},setActive(v){this.active=v;return this},setVisible(){return this},setAlpha(){return this},clearTint(){return this}};let paused=false;
const s={sys:{settings:{key:'game'}},events:new EventEmitter(),input:{enabled:true,keyboard:{enabled:true,resetKeys(){}}},player,physics:{world:{pause(){paused=true},resume(){paused=false}}},time:{now:50},shots:{clear(){}},bullets:{clear(){}},branches:{clear(){}},snareEnemy:object(),capturedWing:object(),rescuedWing:object(),grafted:true,stage:4,weaponLevel:4,extraLivesAwarded:2,run:{wave:3,score:35000,maxStage:4},clearTouchState(){},applyStage(){},updateHud(){},notice:{setVisible(){}},banner(){},create(){this.lives=0;this.run={wave:3,score:35000,maxStage:4};},endRun(){this.ended=true;},togglePause(){this.paused=!this.paused;},damagePlayer(){this.lives--;}};
const game={events,scene:{getScene:()=>s,isActive:()=>!s.ended,isPaused:()=>paused,pause(){paused=true},resume(){paused=false}}};return {s,game};}
test('restoration preserves score, sector and extra-life accounting while resetting combat loadout',()=>{const {s}=sceneFixture();restoreArborwing(s,3);assert.equal(s.lives,3);assert.equal(s.weaponLevel,0);assert.equal(s.stage,0);assert.equal(s.run.score,35000);assert.equal(s.run.wave,3);assert.equal(s.extraLivesAwarded,2);assert.equal(s.grafted,false);assert.equal(s.capturedWing,undefined);assert.equal(s.player.body.enable,true);assert.equal(s.invulnUntil,3050);});
test('missing player body fails preparation',()=>assert.throws(()=>prepareArborwing({run:{}}),/cannot be restored/));
test('scene is paused at life exhaustion; decline uses original game-over path',async()=>{const {s,game}=sceneFixture();let offer;const bridge=wireContinueGame(game,mockApi().api,{offer:o=>offer=o,close(){}});s.create();s.endRun();assert.equal(s.paused,true);assert.equal(s.input.keyboard.enabled,false);assert.equal(s.ended,undefined);await offer.decline();assert.equal(s.ended,true);assert.equal(s.input.keyboard.enabled,true);bridge.destroy();});
test('quick test is explicitly practice and successful continue is one per run',async()=>{const {s,game}=sceneFixture();let offer;const service=mockApi(),bridge=wireContinueGame(game,service.api,{offer:o=>offer=o,close(){}});s.create();assert.equal(bridge.testNow(),true);assert.equal(s.run.practice,true);await offer.attempt.continue();assert.equal(s.lives,3);assert.equal(s.run.continued,true);s.lives=0;s.endRun();assert.equal(s.ended,true);assert.equal(service.calls.filter(c=>c.action==='reserve').length,1);bridge.destroy();});
const gameOrigin='https://deploy-preview-1--treeforce89.netlify.app',authOrigin='https://deploy-preview-18--tree-token.netlify.app';
function proxyFixture(){const calls=[];const h=createCreditsProxy({enabled:'true',authOrigin,gameOrigin,fetcher:async(u,o)=>{calls.push({u,o});return Response.json({status:'ok',ledger:{mode:'simulation',accountId:account},result:{}});}});return {h,calls};}
const req=(body={action:'balance'},options={})=>new Request(`${gameOrigin}/api/canopy-credits`,{method:'POST',headers:{Origin:gameOrigin,'Content-Type':'application/json',Cookie:'__Host-tree-game-session='+'a'.repeat(64),...options},body:JSON.stringify(body)});
test('proxy uses existing HttpOnly session token, never a browser account ID',async()=>{const f=proxyFixture();assert.equal((await f.h(req())).status,200);const forwarded=JSON.parse(f.calls[0].o.body);assert.equal(forwarded.token,'a'.repeat(64));assert.equal(forwarded.accountId,undefined);assert.equal(f.calls[0].o.headers.Origin,undefined);});
test('unsigned request cannot reach ledger',async()=>{const f=proxyFixture();assert.equal((await f.h(req(undefined,{Cookie:''}))).status,401);assert.equal(f.calls.length,0);});
test('foreign-origin purchase fails before upstream',async()=>{const f=proxyFixture();assert.equal((await f.h(req(undefined,{Origin:'https://evil.test'}))).status,403);assert.equal(f.calls.length,0);});
test('simulation is opt-in and unavailable on production origin',async()=>{const f=createCreditsProxy({enabled:'false',authOrigin,gameOrigin});assert.equal((await f(req())).status,503);const prod=createCreditsProxy({enabled:'true',authOrigin,gameOrigin:'https://treeforce89.netlify.app'});assert.equal((await prod(new Request('https://treeforce89.netlify.app/api/canopy-credits'))).status,503);});
test('expired account session remains unauthorized through proxy',async()=>{const f=createCreditsProxy({enabled:'true',authOrigin,gameOrigin,fetcher:async()=>Response.json({error:'sign-in-required'},{status:401})});const r=await f(req());assert.equal(r.status,401);});
test('upstream outage cannot invent a balance or successful payment',async()=>{const f=createCreditsProxy({enabled:'true',authOrigin,gameOrigin,fetcher:async()=>{throw Error('offline')}});assert.equal((await f(req())).status,503);});
test('oversized browser payload is rejected',async()=>{const f=proxyFixture();assert.equal((await f.h(req({junk:'x'.repeat(3000)}))).status,413);assert.equal(f.calls.length,0);});
