import {test} from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {ACHIEVEMENTS,STORAGE_KEY,RULESET,addRun,accuracy,cleanCallsign,createRecordStore,emptyState,eligible,readState,topRuns,validRun,weekStart} from '../app/game/records-core.mjs';
import {wireRecords} from '../app/game/records-game.mjs';
const now=Date.parse('2026-09-08T14:00:00Z');
function run(overrides={}){return {id:'flight-a',ruleset:RULESET,callsign:'PETER',title:'',kind:'normal',reasons:[],score:18000,kills:25,shotsFired:100,shotsHit:80,startWave:1,waveReached:2,wavesCleared:1,cleared:false,endedAt:now,elapsedMs:60000,maxCombo:25,maxGrowth:3,maxWeapon:3,rescues:0,boom:0,ghost:0,perfect:0,...overrides};}
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};};
test('normal flights add real scores; empty boards have no fabricated rows',()=>{const start=emptyState('p',now);assert.equal(start.best.length,0);const r=addRun(start,run());assert.equal(r.state.best[0].score,18000);assert.equal(start.best.length,0);assert.equal(r.newBest,true);});
test('duplicates cannot inflate career or achievements',()=>{const first=addRun(emptyState('p',now),run());const twice=addRun(first.state,run());assert.equal(twice.saved,false);assert.equal(twice.state.career.runs,1);});
test('practice and continued flights are history only',()=>{for(const kind of ['practice','continued']){const result=addRun(emptyState('p',now),run({kind,reasons:[kind]}));assert.equal(result.state.recent.length,1);assert.equal(result.state.best.length,0);assert.equal(result.state.career.runs,0);assert.deepEqual(result.unlocked,[]);}});
test('normal flag cannot override a wave skip or taint',()=>{assert.equal(eligible(run({startWave:2})),false);assert.equal(eligible(run({reasons:['Debug']})),false);});
test('scores are sorted descending with deterministic earlier-first ties',()=>{const rows=topRuns([run({id:'c',score:10,endedAt:now+10}),run({id:'b',score:20}),run({id:'a',score:10})]);assert.deepEqual(rows.map(r=>r.id),['b','a','c']);});
test('only 10 top runs and 50 recent flights retained; career survives pruning',()=>{let s=emptyState('p',now);for(let i=0;i<70;i++)s=addRun(s,run({id:`r${i}`,score:i,endedAt:now+i})).state;assert.equal(s.best.length,10);assert.equal(s.recent.length,50);assert.equal(s.career.runs,70);assert.equal(s.best[0].score,69);});
test('week boundary is Monday 00:00 UTC including year rollover',()=>{assert.equal(weekStart(Date.parse('2026-09-06T23:59:59Z')),'2026-08-31');assert.equal(weekStart(Date.parse('2026-09-07T00:00:00Z')),'2026-09-07');assert.equal(weekStart(Date.parse('2027-01-01T00:00:00Z')),'2026-12-28');});
test('weekly rollover retains all-time records',()=>{let s=addRun(emptyState('p',now),run()).state;s=addRun(s,run({id:'next-week',score:10,endedAt:now+7*864e5})).state;assert.equal(s.weekly.runs.length,1);assert.equal(s.best[0].score,18000);});
test('late older-week records do not roll the current week backwards',()=>{let s=addRun(emptyState('p',now),run()).state;s=addRun(s,run({id:'old',endedAt:now-7*864e5})).state;assert.equal(s.weekly.start,'2026-09-07');assert.equal(s.weekly.runs.length,1);});
test('sharpshooter requires 50 shots; accuracy is not rounded up for award',()=>{for(const [hits,shots,earned] of [[49,49,false],[39,50,false],[40,50,true],[797,1000,false],[0,0,false]]){const r=addRun(emptyState('p',now),run({shotsHit:hits,shotsFired:shots}));assert.equal(r.unlocked.includes('sharpshooter'),earned);}});
test('each gameplay achievement has a working unlock rule',()=>{const r=run({cleared:true,waveReached:10,wavesCleared:10,maxGrowth:5,maxWeapon:5,rescues:1,boom:1,ghost:1,perfect:1});const first=addRun(emptyState('p',now),r);assert.equal(first.unlocked.length,11);let s=first.state;for(let i=0;i<9;i++)s=addRun(s,run({id:`extra${i}`})).state;assert.equal(Object.keys(s.badges).length,12);assert.equal(ACHIEVEMENTS.length,12);});
test('invalid, NaN, negative and incoherent records are rejected',()=>{for(const changes of [{score:NaN},{score:Infinity},{score:-1},{score:1.5},{shotsHit:101},{startWave:0},{waveReached:11},{id:''}])assert.equal(validRun(run(changes)),false);});
test('no-shot accuracy is zero, not NaN',()=>assert.equal(accuracy(run({shotsHit:0,shotsFired:0})),0));
test('callsign sanitizes markup and limits length',()=>{assert.equal(cleanCallsign('<>'),'ARBORIST');assert.equal(cleanCallsign('  Peter_89! '),'Peter_89');assert.equal(cleanCallsign('x'.repeat(30)).length,16);});
test('records survive reloading and cannot equip a locked title',()=>{const mem=memory(),s=createRecordStore(mem,'p',()=>now);s.save(run());s.profile('PETER','canopy-defender');assert.equal(s.get().state.pilot.title,'');s.profile('PETER','first-flight');const loaded=createRecordStore(mem,'other',()=>now).get().state;assert.equal(loaded.pilot.id,'p');assert.equal(loaded.pilot.title,'first-flight');assert.equal(loaded.best.length,1);});
test('storage failure is explicit and does not break gameplay',()=>{const s=createRecordStore({getItem:()=>null,setItem(){throw Error('quota')}},'p',()=>now);s.save(run());assert.equal(s.get().persistent,false);assert.match(s.get().warning,/session only/);assert.equal(s.get().state.best.length,1);});
test('malformed or future storage is preserved instead of overwritten',()=>{let writes=0;for(const raw of ['{bad','{"schema":9}']){const s=createRecordStore({getItem:()=>raw,setItem(){writes++;}},'p',()=>now);s.save(run());assert.equal(s.get().persistent,false);}assert.equal(writes,0);});
test('legacy fixed/unknown high score is not imported',()=>{const mem=memory();mem.setItem('treeforce89-campaign-best-v1','89000');assert.equal(createRecordStore(mem).get().state.best.length,0);});
function fixture(){
 const store=createRecordStore(memory(),'p',()=>now),events=new EventEmitter();
 const keys=new EventEmitter();keys.enabled=true;
 const s={sys:{settings:{key:'game'}},events:new EventEmitter(),input:{keyboard:keys},children:{list:[{text:'HI\n089000',setText(t){this.text=t;}}]},physics:{world:{isPaused:false,timeScale:1}},time:{timeScale:1},debugPanel:{list:[]},
 create(){this.run={score:100,kills:1,shotsHit:1,shotsFired:2,maxStage:0,wave:0,perfect:0};this.paused=false;this.invincible=false;this.debug=false;this.weaponLevel=0;this.chain=1;this.grafted=false;},
 roundSequence(){},endRun(){},hitEnemy(){this.chain=25;},collectWeaponCore(){this.weaponLevel=4;},grow(){this.run.maxStage=4;},collectBoom(p){p.active=false;},collectSovereignShield(p){p.active=false;},rescueCapturedWing(){this.grafted=true;},};
 let paused=false;const game={events,scene:{getScene:()=>s,getScenes:()=>[s],pause:()=>{paused=true;},isPaused:()=>paused,resume:()=>{paused=false;}}};
 const bridge=wireRecords(game,store);s.create();return {s,store,game,bridge,keys};
}
test('game adapter replaces fixed HI score and saves on endRun',()=>{const f=fixture();assert.equal(f.s.children.list[0].text,'BEST\n000000');f.s.events.emit('postupdate',100,16);f.s.endRun(false);assert.equal(f.store.get().state.best[0].score,100);assert.equal(f.store.get().state.best[0].elapsedMs,16);f.bridge.destroy();});
test('debug taint remains after toggle is switched off',()=>{const f=fixture();f.keys.emit('keydown-BACKTICK');f.s.debug=false;f.s.invincible=false;f.s.endRun(false);assert.equal(f.store.get().state.best.length,0);assert.equal(f.store.get().state.recent[0].kind,'practice');assert.equal(f.s.run.practice,true);});
test('wave-select practice cannot earn badges',()=>{const f=fixture();f.keys.emit('keydown-BACKTICK');f.s.run.wave=9;f.s.roundSequence();f.s.endRun(true);assert.equal(Object.keys(f.store.get().state.badges).length,0);});
test('collecting BOOM/ghost, rescuing, combo and weapon peaks are captured',()=>{const f=fixture();f.s.collectBoom({active:true});f.s.collectSovereignShield({active:true});f.s.rescueCapturedWing();f.s.collectWeaponCore();f.s.hitEnemy();f.s.grow();f.s.weaponLevel=0;f.s.endRun(false);const r=f.store.get().state.best[0];assert.equal(r.boom,1);assert.equal(r.ghost,1);assert.equal(r.rescues,1);assert.equal(r.maxCombo,25);assert.equal(r.maxWeapon,5);assert.equal(r.maxGrowth,5);});
test('continue boundary freezes the original score before later casual gains',()=>{const f=fixture();f.game.events.emit('arcade:continue-authorized');f.s.run.score=999999;f.s.endRun(true);const s=f.store.get().state;assert.equal(s.best[0].score,100);assert.equal(s.recent[0].kind,'continued');assert.equal(s.career.runs,1);});
test('panel pauses scene and keyboard, then restores both',()=>{const f=fixture();f.bridge.visibility(true);assert.equal(f.game.scene.isPaused(),true);assert.equal(f.keys.enabled,false);f.bridge.visibility(false);assert.equal(f.game.scene.isPaused(),false);assert.equal(f.keys.enabled,true);});
test('paused time is excluded',()=>{const f=fixture();f.s.paused=true;f.s.events.emit('postupdate',100,100);f.s.paused=false;f.s.events.emit('postupdate',116,16);f.s.endRun(false);assert.equal(f.store.get().state.best[0].elapsedMs,16);});
test('replaying starts a fresh record and removes old scene listeners on shutdown',()=>{const f=fixture();f.s.endRun();f.s.events.emit('shutdown');f.s.create();f.s.endRun();assert.equal(f.store.get().state.career.runs,2);assert.equal(f.s.events.listenerCount('postupdate'),1);});
