import {test} from 'node:test';import assert from 'node:assert/strict';import {createInlineProxy} from '../netlify/lib/tree-account-inline.mjs';
const gameOrigin='https://deploy-preview-1--treeforce89.netlify.app',authOrigin='https://deploy-preview-18--tree-token.netlify.app',now=2000000000000;
const identity={authenticated:true,environment:'preview',accountId:'12345678-1234-4234-8234-123456789abc',wallet:{family:'sui',address:'0x'+'1'.repeat(64)},expiresAt:now+1800000};
const req=(body,cookie='',extra={})=>new Request(gameOrigin+'/api/tree-account-inline',{method:'POST',headers:{'Content-Type':'application/json',Origin:gameOrigin,Cookie:cookie,...extra},body:JSON.stringify(body)});
function fixture(){const calls=[];const h=createInlineProxy({authOrigin,gameOrigin,now:()=>now,fetcher:async(url,o)=>{const b=JSON.parse(o.body);calls.push(b);assert.equal(o.headers.Origin,undefined);return Response.json(b.action==='challenge'?{status:'ok',nonce:'a'.repeat(64),binding:'b'.repeat(64),expiresAt:now+300000,message:'Sign in only'}:b.action==='verify'?{status:'ok',accessToken:'c'.repeat(64),identity}:{status:'ok'})}});return{h,calls,async challenge(){return h(req({action:'challenge',family:'sui',address:'0x1',chainId:'sui:mainnet'}))}}}
const cookie=r=>r.headers.getSetCookie()[0].split(';')[0];
test('challenge hides secret binding in secure host-only cookie, not JSON',async()=>{const f=fixture(),r=await f.challenge(),p=await r.json();assert.equal(p.binding,undefined);assert.equal(p.nonce,undefined);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);assert.equal(p.message,'Sign in only')});
test('verified session uses existing cookie name and returns no access token',async()=>{const f=fixture(),r=await f.h(req({action:'verify',signature:'signed'},cookie(await f.challenge()))),p=await r.json();assert.equal(p.identity.accountId,identity.accountId);assert.equal(p.accessToken,undefined);assert.match(r.headers.get('set-cookie'),/__Host-tree-game-session=/);assert.equal(f.calls.at(-1).binding,'b'.repeat(64))});
test('verify without browser proof cookie is rejected',async()=>{const f=fixture();assert.equal((await f.h(req({action:'verify',signature:'x'}))).status,401);assert.equal(f.calls.length,0)});
test('client cannot choose nonce binding account or token',async()=>{const f=fixture();for(const key of ['nonce','binding','accountId','accessToken','clientOrigin'])assert.equal((await f.h(req({action:'verify',signature:'x',[key]:'forged'}))).status,400)});
test('cancel clears only pending proof cookie, not current signed-in session',async()=>{const f=fixture(),c=cookie(await f.challenge());const r=await f.h(req({action:'cancel'},c+'; __Host-tree-game-session='+'d'.repeat(64)));assert.match(r.headers.get('set-cookie'),/__Host-tree-game-inline=;/);assert.doesNotMatch(r.headers.get('set-cookie'),/tree-game-session/);assert.equal(f.calls.at(-1).action,'cancel')});
test('CSRF foreign origin and invalid content type fail before any upstream call',async()=>{const f=fixture();assert.equal((await f.h(req({action:'challenge'},'',{Origin:'https://evil.example'}))).status,403);assert.equal((await f.h(req({action:'challenge'},'',{'Content-Type':'text/plain'}))).status,415);assert.equal(f.calls.length,0)});
test('oversized stream and non-preview deployment are rejected',async()=>{const f=fixture();assert.equal((await f.h(req({action:'verify',signature:'x'.repeat(16000)}))).status,413);const h=createInlineProxy({authOrigin,gameOrigin:'https://treeforce89.netlify.app'});assert.equal((await h(new Request('https://treeforce89.netlify.app/api/tree-account-inline'))).status,503)});
test('upstream timeout never sets a session or fabricated identity',async()=>{const h=createInlineProxy({authOrigin,gameOrigin,fetcher:async()=>{throw Error('offline')}});const r=await h(req({action:'challenge',family:'sui',address:'0x1',chainId:'sui:mainnet'}));assert.equal(r.status,503);assert.equal(r.headers.has('set-cookie'),false)});
