import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createGameSessionHandler} from '../netlify/lib/tree-account-session.mjs';
const gameOrigin='https://game.example.test',authOrigin='https://accounts.example.test';
const identity={authenticated:true,accountId:'12345678-1234-4234-8234-123456789abc',environment:'preview',wallet:{family:'sui',address:'0x'+'1'.repeat(64)},expiresAt:2000000600000,entitlement:'not-checked'};
function fixture(){const calls=[];const handle=createGameSessionHandler({authOrigin,gameOrigin,now:()=>2000000000000,fetcher:async(url,options)=>{calls.push({url,options,body:JSON.parse(options.body)});return Response.json({status:'ok',accessToken:'a'.repeat(64),identity});}});return {handle,calls};}
function request(body,cookie='',path='/api/tree-account',origin=gameOrigin){return new Request(gameOrigin+path,{method:body?'POST':'GET',headers:{Cookie:cookie,...(body?{'Content-Type':'application/json',Origin:origin}:{})},...(body?{body:JSON.stringify(body)}:{})});}
test('anonymous game session is safe and requires no upstream call',async()=>{const f=fixture(),r=await f.handle(request());assert.equal((await r.json()).identity,null);assert.equal(f.calls.length,0);});
test('begin keeps verifier in HttpOnly cookie, not login URL',async()=>{const f=fixture(),r=await f.handle(request({action:'begin'})),p=await r.json(),u=new URL(p.url);assert.equal(u.origin,authOrigin);assert.equal(u.searchParams.has('verifier'),false);assert.equal(u.searchParams.get('codeChallenge').length,43);assert.match(r.headers.get('set-cookie'),/HttpOnly; Secure; SameSite=Lax/);});
test('correct callback exchanges one-use code, returns no access token to JS',async()=>{const f=fixture(),r=await f.handle(request({action:'begin'})),p=await r.json(),state=new URL(p.url).searchParams.get('state'),cookie=r.headers.get('set-cookie').split(';')[0];const callback=await f.handle(request(null,cookie,`/api/tree-account/callback?state=${state}&code=${'b'.repeat(64)}`));assert.equal(callback.status,303);assert.equal(callback.headers.get('location'),'/account-return.html');assert.match(callback.headers.get('set-cookie'),/__Host-tree-game-session=/);assert.equal((await callback.text()).includes('a'.repeat(64)),false);assert.equal(f.calls[0].body.action,'exchange');assert.equal(f.calls[0].options.headers.Origin,undefined);});
test('wrong callback state never reaches central service',async()=>{const f=fixture(),r=await f.handle(request({action:'begin'})),cookie=r.headers.get('set-cookie').split(';')[0];const callback=await f.handle(request(null,cookie,`/api/tree-account/callback?state=${'f'.repeat(64)}&code=${'b'.repeat(64)}`));assert.match(callback.headers.get('location'),/error=/);assert.equal(f.calls.length,0);});
test('identity is fetched from central session, not an account ID supplied by browser',async()=>{const f=fixture(),r=await f.handle(request(null,'__Host-tree-game-session='+'b'.repeat(64)));assert.equal((await r.json()).identity.accountId,identity.accountId);assert.equal(f.calls[0].body.token,'b'.repeat(64));});
test('foreign-origin and unsupported actions fail',async()=>{const f=fixture();assert.equal((await f.handle(request({action:'begin'},'','/api/tree-account','https://evil.test'))).status,403);assert.equal((await f.handle(request({action:'set-account',accountId:identity.accountId}))).status,400);});
test('missing config never fabricates a signed-in account',async()=>{const h=createGameSessionHandler({});assert.equal((await h(request())).status,503);});
test('central revocation clears game session cookie',async()=>{const h=createGameSessionHandler({authOrigin,gameOrigin,fetcher:async()=>Response.json({status:'error',error:'sign-in-required'},{status:401})});const r=await h(request(null,'__Host-tree-game-session='+'b'.repeat(64)));assert.equal((await r.json()).identity,null);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
test('upstream outage is not treated as authenticated',async()=>{const h=createGameSessionHandler({authOrigin,gameOrigin,fetcher:async()=>{throw Error('offline')}});assert.equal((await h(request(null,'__Host-tree-game-session='+'b'.repeat(64)))).status,503);});
test('sign-out revokes central child token without exposing it',async()=>{const f=fixture(),r=await f.handle(request({action:'logout'},'__Host-tree-game-session='+'b'.repeat(64)));assert.equal((await r.json()).identity,null);assert.equal(f.calls[0].body.action,'game-logout');assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
