import * as Phaser from "phaser";
import {E} from "./events";import {enemyConfig,GAME_VERSION,H,palette,stages,tuning,W,waves,weaponLevels} from "./config";import {SeededRng} from "./rng";

const {css:pc,hex:ph}=palette;
const font=(size=12,color:string=pc.text)=>({fontFamily:"Verdana, Arial, sans-serif",fontSize:`${Math.max(size,11)}px`,fontStyle:"bold",color,stroke:"#020906",strokeThickness:size>=15?3:2});
let audioContext:AudioContext|undefined,sfxMuted=false;
type Kind="bat"|"borer"|"spore"|"small";
interface Enemy extends Phaser.Physics.Arcade.Sprite{kind:Kind;hp:number;homeX:number;homeY:number;phase:number;diving:boolean;settled:boolean;returning:boolean;formationIndex:number;lastFire:number}
interface RunState{runId:string;seed:number;score:number;wave:number;kills:number;perfect:number;maxStage:number;shotsFired:number;shotsHit:number;start:number;mode:string}

class BootScene extends Phaser.Scene{constructor(){super("boot")}preload(){this.load.image("hero-photo","/assets/hero/tree-hero-canonical.jpg");this.load.image("forest-back","/assets/backgrounds/first-canopy-backdrop.png");this.load.image("forest-mid","/assets/backgrounds/first-canopy-midground.png");this.load.image("forest-front","/assets/backgrounds/first-canopy-foreground.png");this.load.image("victoryTurbo","/assets/powerups/dex-reward-token.jpeg");this.load.spritesheet("playerSheet","/assets/arborwing/tree-hero-arborwing-stages-v2.png",{frameWidth:128,frameHeight:160})}create(){makeTextures(this);this.scene.start("title")}}

class TitleScene extends Phaser.Scene{
 constructor(){super("title")}
 create(){
  forest(this);this.add.rectangle(240,360,480,720,ph.bg,.28);
  const photo=this.add.image(240,434,"hero-photo").setDisplaySize(285,390).setAlpha(.72).setTint(0xb9ffbc);
  this.tweens.add({targets:photo,y:428,duration:1800,yoyo:true,repeat:-1,ease:"Sine.inOut"});
  this.add.text(240,75,"TREE FORCE ’89",font(38,pc.green)).setOrigin(.5).setShadow(4,4,pc.cyan,4);
  this.add.text(240,117,"CANOPY COMMAND",font(19,pc.gold)).setOrigin(.5);
  this.add.text(240,153,"GROW. SHIELD. DEFEND THE CANOPY.",font(10,pc.muted)).setOrigin(.5);
  this.add.text(240,650,this.sys.game.device.input.touch?"TAP TO PLANT":"PRESS SPACE TO PLANT",font(15,pc.text)).setOrigin(.5).setDepth(5);
  this.add.text(240,685,"© 1989 TREE FORCE LABS",font(8,"#5c7b8b")).setOrigin(.5);
  this.input.once("pointerdown",()=>this.scene.start("game"));this.input.keyboard?.once("keydown-SPACE",()=>this.scene.start("game"));
 }
}

class GameScene extends Phaser.Scene{
 player!:Phaser.Physics.Arcade.Sprite;shots!:Phaser.Physics.Arcade.Group;enemies!:Phaser.Physics.Arcade.Group;bullets!:Phaser.Physics.Arcade.Group;branches!:Phaser.Physics.Arcade.Group;pickups!:Phaser.Physics.Arcade.Group;
 stage=0;weaponLevel=0;growth=0;pruneCharge=0;lives=3;chain=0;chainUntil=0;lastShot=0;lastAutoShot=0;turboUntil=0;invulnUntil=0;pruneKills=0;waveSpawned=0;waveStart=0;waveKillsStart=0;waveClearing=false;waveDamage=false;nextDiveAt=0;nextEnemyFireAt=0;captureUsed=false;capturedStage=0;grafted=false;paused=false;dragging=false;dragLast=0;dragPointerId=-1;firePointerId=-1;fireHeld=false;controllerFireHeld=false;gamepadFireWasDown=false;gamepadSelectWasDown=false;gamepadStartWasDown=false;gamepadTaught=false;autoFire=false;invincible=false;hitboxes=false;debug=false;coords=false;showFps=false;pruneTaught=false;pruneReadyAnnounced=false;seedTaught=false;coreTaught=false;turboTaught=false;boomTaught=false;killsSinceSeed=0;killsSinceCore=0;killsSinceTurbo=0;killsSinceBoom=0;volley=0;attackSerial=0;rushTargets=0;rushDestroyed=0;rushShotsFired=0;rushShotsHit=0;wingSide=1;run!:RunState;rng!:SeededRng;snareEnemy?:Enemy;snareBeam?:Phaser.GameObjects.Rectangle;capturedWing?:Phaser.Physics.Arcade.Sprite;rescuedWing?:Phaser.GameObjects.Sprite;clearedRows=new Set<number>();escortKills=new Map<number,number>();escortTargets=new Map<number,number>();
 scoreText!:Phaser.GameObjects.Text;waveText!:Phaser.GameObjects.Text;badgeText!:Phaser.GameObjects.Text;stageText!:Phaser.GameObjects.Text;powerText!:Phaser.GameObjects.Text;lessonText!:Phaser.GameObjects.Text;turboText!:Phaser.GameObjects.Text;pickupText!:Phaser.GameObjects.Text;sfxText!:Phaser.GameObjects.Text;sfxButtonBg!:Phaser.GameObjects.Rectangle;chainText!:Phaser.GameObjects.Text;growthText!:Phaser.GameObjects.Text;pruneChargeText!:Phaser.GameObjects.Text;livesText!:Phaser.GameObjects.Text;notice!:Phaser.GameObjects.Text;autoText!:Phaser.GameObjects.Text;autoButtonBg!:Phaser.GameObjects.Rectangle;fireText!:Phaser.GameObjects.Text;fireButton!:Phaser.GameObjects.Container;fireButtonBg!:Phaser.GameObjects.Rectangle;pruneText!:Phaser.GameObjects.Text;pruneButton!:Phaser.GameObjects.Container;pruneButtonBg!:Phaser.GameObjects.Rectangle;debugPanel!:Phaser.GameObjects.Container;fpsText!:Phaser.GameObjects.Text;coordText!:Phaser.GameObjects.Text;
 constructor(){super("game")}
 create(){
  forest(this);this.makeGroups();const seed=(Date.now()>>>0);this.rng=new SeededRng(seed);this.run={runId:`grove-${seed.toString(16)}`,seed,score:0,wave:0,kills:0,perfect:0,maxStage:0,shotsFired:0,shotsHit:0,start:Date.now(),mode:"ARCADE"};this.events.emit(E.RUN_STARTED,this.run);
  this.player=this.physics.add.sprite(240,570,"playerSheet",0).setDepth(4).setScale(stages[0].scale).setCollideWorldBounds(true);this.player.body!.setSize(18,26);
  this.makeHud();this.bindInput();this.bindCollisions();this.startWave(0);this.time.delayedCall(900,()=>this.setLesson("1/4  MOVE LEFT + RIGHT",2400));this.time.delayedCall(3900,()=>this.setLesson("2/4  FIRE: LEFT CLICK, Z/X, OR CONTROLLER A/B",2600));this.time.delayedCall(6900,()=>this.setLesson("3/4  MISSED SHOTS MUST LEAVE THE SCREEN",3000));
  this.physics.world.on("worldbounds",(body:Phaser.Physics.Arcade.Body)=>{const o=body.gameObject as Phaser.Physics.Arcade.Sprite;if(o.active&&(o.texture.key==="sap"||o.getData("hostile")||o.texture.key==="branch"))o.destroy()});
  this.game.events.on(Phaser.Core.Events.BLUR,this.autoPause,this);this.game.events.on(Phaser.Core.Events.HIDDEN,this.autoPause,this);
 }
 shutdown(){this.game.events.off(Phaser.Core.Events.BLUR,this.autoPause,this);this.game.events.off(Phaser.Core.Events.HIDDEN,this.autoPause,this)}
 makeGroups(){this.shots=this.physics.add.group({maxSize:90});this.enemies=this.physics.add.group();this.bullets=this.physics.add.group();this.branches=this.physics.add.group();this.pickups=this.physics.add.group()}
 makeHud(){
  this.add.rectangle(240,34,480,68,ph.bg,.98).setStrokeStyle(1,ph.green,.48).setDepth(8);this.scoreText=this.add.text(12,7,"SCORE\n000000",font(14)).setDepth(9);this.add.text(240,7,"HI\n089000",font(14,pc.gold)).setOrigin(.5,0).setAlign("center").setDepth(9);this.badgeText=this.add.text(240,53,"◆",font(10,pc.green)).setOrigin(.5).setDepth(9);this.waveText=this.add.text(468,7,"WAVE\n01",font(14)).setOrigin(1,0).setAlign("right").setDepth(9);this.sfxButtonBg=this.add.rectangle(62,54,50,21,ph.panel,1).setStrokeStyle(1,ph.gold).setInteractive().setDepth(10);this.sfxText=this.add.text(62,54,"SFX ON",font(8,pc.gold)).setOrigin(.5).setDepth(11);this.sfxButtonBg.on("pointerdown",()=>this.toggleSfx());
  this.add.rectangle(240,679,480,82,ph.bg,.985).setStrokeStyle(1,ph.green,.55).setDepth(8);this.stageText=this.add.text(12,640,"GROWTH 1/5 // SEEDLING  ×1.00",font(12,pc.green)).setDepth(9);this.powerText=this.add.text(12,657,"WEAPON 1/5 // SAP POD",font(10,pc.gold)).setDepth(9);this.chainText=this.add.text(468,640,"CHAIN 0  ×1.00",font(12,pc.cyan)).setOrigin(1,0).setDepth(9);this.livesText=this.add.text(468,657,"♠ ♠ ♠",font(14,pc.green)).setOrigin(1,0).setDepth(9);this.lessonText=this.add.text(240,82,"",font(14,pc.text)).setOrigin(.5).setDepth(15).setBackgroundColor("#020906").setPadding(12,7,12,7);
  this.growthText=this.add.text(58,678,"GROW 0 / 10",font(10,pc.text)).setOrigin(.5).setDepth(10);this.add.rectangle(58,714,92,8,ph.bgSoft).setStrokeStyle(1,ph.green,.9).setDepth(10);this.notice=this.add.text(240,116,"",font(16,pc.text)).setOrigin(.5).setAlign("center").setDepth(12).setBackgroundColor("#020906").setPadding(10,6,10,6).setVisible(false);this.turboText=this.add.text(468,82,"",font(10,pc.gold)).setOrigin(1,0).setDepth(20).setBackgroundColor("#020906").setPadding(5,3,5,3).setVisible(false);this.pickupText=this.add.text(240,350,"",font(18,pc.gold)).setOrigin(.5).setAlign("center").setDepth(23).setBackgroundColor("#020906").setPadding(12,8,12,8).setVisible(false);
  const help=this.add.circle(116,700,10,ph.panel,.99).setStrokeStyle(2,ph.gold).setInteractive().setDepth(11);this.add.text(116,700,"?",font(11,pc.gold)).setOrigin(.5).setDepth(12);help.on("pointerdown",()=>this.showPruneGuide());
  this.autoButtonBg=this.add.rectangle(166,700,96,34,ph.panel,1).setStrokeStyle(2,ph.gold).setInteractive().setDepth(11);this.autoText=this.add.text(166,700,"AUTO FIRE\nTAP TO ON",font(8,pc.text)).setOrigin(.5).setAlign("center").setDepth(12);this.autoButtonBg.on("pointerdown",()=>this.toggleAutoFire());
  this.pruneButtonBg=this.add.rectangle(267,700,118,34,ph.bgSoft,.99).setStrokeStyle(2,ph.cyan).setInteractive();this.pruneChargeText=this.add.text(267,700,"",font(9,pc.text)).setOrigin(.5);this.pruneText=this.add.text(267,700,"SHIELD 0%",font(9,pc.green)).setOrigin(.5);this.pruneButton=this.add.container(0,0,[this.pruneButtonBg,this.pruneChargeText,this.pruneText]).setDepth(11);this.pruneButtonBg.on("pointerdown",()=>this.prune());
  this.fireButtonBg=this.add.rectangle(400,700,140,34,ph.bgSoft,.99).setStrokeStyle(2,ph.green).setInteractive();this.fireText=this.add.text(400,700,"FIRE\nHOLD / TAP",font(9,pc.green)).setOrigin(.5).setAlign("center");this.fireButton=this.add.container(0,0,[this.fireButtonBg,this.fireText]).setDepth(11);this.fireButtonBg.on("pointerdown",(pointer:Phaser.Input.Pointer)=>{this.firePointerId=pointer.id;this.fireHeld=true;this.fire()});
  this.fpsText=this.add.text(8,76,"",font(8,pc.green)).setDepth(20);this.coordText=this.add.text(8,90,"",font(8,pc.gold)).setDepth(20);this.makeDebug();this.updateHud();this.updateAutoHud();
 }
 bindInput(){
  this.input.addPointer(2);
  const kb=this.input.keyboard!,fireDown=()=>{this.fireHeld=true;this.fire()},fireUp=()=>this.fireHeld=false;kb.addKey("Z").on("down",fireDown).on("up",fireUp);kb.addKey("X").on("down",fireDown).on("up",fireUp);kb.addKey("SPACE").on("down",()=>this.prune());kb.addKey("ESC").on("down",()=>this.togglePause());kb.addKey("BACKTICK").on("down",()=>{this.debug=!this.debug;this.debugPanel.setVisible(this.debug)});
  const stopDrag=(p:Phaser.Input.Pointer)=>{if(p.id===this.dragPointerId){this.dragging=false;this.dragPointerId=-1}};this.input.on("pointerdown",(p:Phaser.Input.Pointer)=>{const isMouse=p.event instanceof MouseEvent;if(isMouse&&p.button===0&&p.y>=155&&p.y<=620){p.event?.preventDefault();this.firePointerId=p.id;this.fireHeld=true;this.fire(true);return}if(!isMouse&&p.y<=620&&this.dragPointerId<0){p.event?.preventDefault();this.dragging=true;this.dragPointerId=p.id;this.dragLast=p.x}});this.input.on("pointermove",(p:Phaser.Input.Pointer)=>{if(this.dragging&&p.id===this.dragPointerId&&p.isDown){p.event?.preventDefault();const dx=p.x-this.dragLast;this.player.x=Phaser.Math.Clamp(this.player.x+dx,35,445);this.dragLast=p.x}});this.input.on("pointerup",(p:Phaser.Input.Pointer)=>{stopDrag(p);if(p.id===this.firePointerId){this.fireHeld=false;this.firePointerId=-1}});this.input.on("pointerout",stopDrag);
 }
 clearTouchState(){this.dragging=false;this.dragPointerId=-1;this.dragLast=0;this.fireHeld=false;this.firePointerId=-1}
 bindCollisions(){
  this.physics.add.overlap(this.shots,this.enemies,(a,b)=>{const shot=a as Phaser.Physics.Arcade.Sprite,e=b as Enemy,hits=shot.getData("hitIds") as Set<Enemy>;if(hits?.has(e))return;hits?.add(e);if(!shot.getData("countedHit")){shot.setData("countedHit",true);this.run.shotsHit++;if(this.isCanopyRush())this.rushShotsHit++}this.hitEnemy(e,shot.getData("damage")||1,false);const pierce=shot.getData("pierce")||0;if(pierce>0)shot.setData("pierce",pierce-1);else shot.destroy()});
  this.physics.add.overlap(this.branches,this.enemies,(_,b)=>this.hitEnemy(b as Enemy,6,true));
  this.physics.add.overlap(this.branches,this.bullets,(_,b)=>{leafBurst(this,(b as Phaser.Physics.Arcade.Sprite).x,(b as Phaser.Physics.Arcade.Sprite).y);b.destroy()});
  this.physics.add.overlap(this.player,this.pickups,(_,p)=>this.collectPickup(p as Phaser.Physics.Arcade.Sprite));
  this.physics.add.overlap(this.player,this.bullets,(_,b)=>{b.destroy();this.damagePlayer()});this.physics.add.overlap(this.player,this.enemies,(_,b)=>{(b as Enemy).destroy();this.damagePlayer()});
 }
 update(time:number,delta:number){
  if(this.paused)return;if(this.dragPointerId>=0&&!this.input.manager.pointers.some(p=>p.id===this.dragPointerId&&p.isDown))this.clearTouchState();const turbo=this.turboUntil>time,curs=this.input.keyboard!.createCursorKeys(),keys=this.input.keyboard!.addKeys("A,D") as Record<string,Phaser.Input.Keyboard.Key>;let dir=0;if(curs.left.isDown||keys.A.isDown)dir--;if(curs.right.isDown||keys.D.isDown)dir++;const pad=typeof navigator!=="undefined"?Array.from(navigator.getGamepads?.()||[]).find((p):p is Gamepad=>!!p):undefined;if(pad){const left=!!pad.buttons[14]?.pressed||pad.axes[0]<-.45,right=!!pad.buttons[15]?.pressed||pad.axes[0]>.45,fire=!!pad.buttons[0]?.pressed||!!pad.buttons[1]?.pressed,select=!!pad.buttons[8]?.pressed,start=!!pad.buttons[9]?.pressed;if(left)dir--;if(right)dir++;if(fire&&!this.gamepadFireWasDown)this.fire(true);if(select&&!this.gamepadSelectWasDown)this.prune();if(start&&!this.gamepadStartWasDown)this.togglePause();this.controllerFireHeld=fire;this.gamepadFireWasDown=fire;this.gamepadSelectWasDown=select;this.gamepadStartWasDown=start;if(!this.gamepadTaught){this.gamepadTaught=true;this.setLesson("CONTROLLER READY // D-PAD MOVE · A/B FIRE · SELECT SHIELD · START PAUSE",3200)}}else{this.controllerFireHeld=false;this.gamepadFireWasDown=false;this.gamepadSelectWasDown=false;this.gamepadStartWasDown=false}this.player.setVelocityX(dir*stages[this.stage].speed*(turbo?tuning.turboMoveMultiplier:1));
  const repeatMs=(this.autoFire?tuning.autoFireMs:tuning.holdFireMs)*(turbo?tuning.turboFireMultiplier:1);if((this.autoFire||this.fireHeld||this.controllerFireHeld)&&time-this.lastAutoShot>=repeatMs){this.fire();this.lastAutoShot=time}if(this.chain&&time>this.chainUntil){this.chain=0;this.events.emit(E.CHAIN_CHANGED,0);this.updateHud()}
  this.updateEnemies(time,delta);this.updateCapture(time);this.updateHostileBullets(time,delta);this.updatePickups(delta);this.updateWaves(time);this.drawMeters();this.updateFireHud();this.turboText.setText(turbo?`VICTORY TURBO ${Math.ceil((this.turboUntil-time)/1000)}s`:"");if(this.player.active)this.player.setAlpha(time<this.invulnUntil&&Math.floor(time/80)%2===0?.28:1);this.fpsText.setText(this.showFps?`FPS ${Math.round(this.game.loop.actualFps)}`:"");this.coordText.setText(this.coords?`X ${Math.round(this.player.x)}  Y ${Math.round(this.player.y)}`:"");
 }
 fire(rapidClick=false){if(!this.player.active||this.waveClearing||this.paused)return;const weapon=weaponLevels[this.weaponLevel],now=this.time.now,turbo=this.turboUntil>now,shooters=this.grafted&&this.rescuedWing?.active?[this.player,this.rescuedWing]:[this.player],points=this.weaponPoints(),needed=points.length*shooters.length,cap=(weapon.activeCap+(rapidClick?2:0))*shooters.length,cooldown=rapidClick?80:weapon.fireMs*(turbo?tuning.turboFireMultiplier:1);if(now-this.lastShot<cooldown||this.shots.countActive()+needed>cap)return;this.lastShot=now;this.volley++;shooters.forEach(shooter=>points.forEach(p=>{const shot=this.shots.get(shooter.x+p.x,shooter.y+p.y,"sap") as Phaser.Physics.Arcade.Sprite;if(!shot)return;shot.setActive(true).setVisible(true).setDepth(3);shot.body!.enable=true;shot.setVelocity(0,-weapon.speed).setCollideWorldBounds(true).setData("damage",weapon.damage).setData("pierce",weapon.pierce).setData("hitIds",new Set<Enemy>()).setData("countedHit",false);if(weapon.damage>1)shot.setScale(1.45,1.7).setTint(0xf2ff89);else if(weapon.pierce)shot.setScale(1.15,1.4).setTint(0xbaff9a);else shot.setScale(1).clearTint();(shot.body as Phaser.Physics.Arcade.Body).onWorldBounds=true;this.run.shotsFired++;if(this.isCanopyRush())this.rushShotsFired++;const flash=this.add.circle(shooter.x+p.x,shooter.y+p.y,2.2,turbo?ph.cyan:ph.gold,.95).setStrokeStyle(1,ph.green).setDepth(7);this.tweens.add({targets:flash,scale:2.2,alpha:0,duration:90,onComplete:()=>flash.destroy()})}));tone(this,turbo?760:620,.025,.03)}
 branchMount(){return[
  {x:9,y:15},
  {x:14,y:13},
  {x:18,y:8},
  {x:21,y:1},
  {x:25,y:-8},
 ][this.stage]}
 weaponPoints(){const side=this.volley%2===0?-1:1,m=this.branchMount(),scale=stages[this.stage].scale,sides=weaponLevels[this.weaponLevel].shots===1?[side]:[-1,1];return sides.map(s=>({x:s*m.x*scale,y:m.y*scale}))}
 updateFireHud(){if(!this.fireText)return;const fighters=this.grafted&&this.rescuedWing?.active?2:1,cap=weaponLevels[this.weaponLevel].activeCap*fighters;this.fireText.setText(`FIRE\n${this.shots.countActive()} / ${cap}`)}
 toggleAutoFire(){this.autoFire=!this.autoFire;this.fireHeld=false;this.firePointerId=-1;this.lastAutoShot=this.time.now;if(this.autoFire)this.fire();this.updateAutoHud();this.setLesson(this.autoFire?"AUTO FIRE ON // SLOWER, CAPPED, STRAIGHT AHEAD":"AUTO FIRE OFF // MANUAL FIRE IS FASTEST",1900)}
 updateAutoHud(){if(!this.autoText)return;this.autoText.setText(this.autoFire?"AUTO FIRE\nON":"AUTO FIRE\nTAP TO ON").setColor(this.autoFire?pc.gold:pc.text);this.autoButtonBg.setStrokeStyle(3,this.autoFire?ph.green:ph.gold)}
 toggleSfx(){sfxMuted=!sfxMuted;this.sfxText.setText(sfxMuted?"SFX OFF":"SFX ON").setColor(sfxMuted?pc.muted:pc.gold);this.sfxButtonBg.setStrokeStyle(1,sfxMuted?ph.muted:ph.gold);if(!sfxMuted)tone(this,760,.07,.05)}
 addGrowth(n:number){if(this.stage===4)return;this.growth+=n;if(this.growth>=stages[this.stage].need)this.grow();this.updateHud()}
 maybeDropGrowthSeed(x:number,y:number,kind:Kind){
  this.killsSinceSeed++;const chance={bat:.24,borer:.72,spore:.58,small:.12}[kind],guaranteed=this.killsSinceSeed>=4;if(!guaranteed&&this.rng.next()>chance)return;this.killsSinceSeed=0;const value={bat:5,borer:10,spore:8,small:3}[kind];const seed=this.pickups.create(x,y,"growthSeed") as Phaser.Physics.Arcade.Sprite;seed.setDepth(5).setData("pickupType","growth").setData("growthValue",value).setData("spin",this.rng.range(-.12,.12)).setVelocity(this.rng.range(-24,24),78);if(!this.seedTaught){this.seedTaught=true;this.setLesson("GROWTH SEED // EXPANDS ARBORWING",2800)}
 }
 maybeDropWeaponCore(x:number,y:number,kind:Kind){if(this.weaponLevel===weaponLevels.length-1)return;this.killsSinceCore++;const chance={bat:.04,borer:.25,spore:.2,small:.01}[kind],guaranteed=this.killsSinceCore>=tuning.weaponCorePity;if(!guaranteed&&this.rng.next()>chance)return;this.killsSinceCore=0;const core=this.pickups.create(x,y,"weaponCore") as Phaser.Physics.Arcade.Sprite;core.setDepth(6).setData("pickupType","weapon").setData("spin",this.rng.range(-.18,.18)).setVelocity(this.rng.range(-18,18),68);if(!this.coreTaught){this.coreTaught=true;this.setLesson("WEAPON CORE // PRECISION POWER, NOT SPREAD",3000)}}
 maybeDropVictoryTurbo(x:number,y:number,kind:Kind){this.killsSinceTurbo++;const chance={bat:.018,borer:.09,spore:.07,small:.006}[kind],guaranteed=this.killsSinceTurbo>=tuning.turboPity;if(!guaranteed&&this.rng.next()>chance)return;this.killsSinceTurbo=0;const token=this.pickups.create(x,y,"victoryTurbo") as Phaser.Physics.Arcade.Sprite;token.setScale(.115).setDepth(6).setData("pickupType","turbo").setData("spin",this.rng.range(-.15,.15)).setVelocity(this.rng.range(-14,14),58);token.body?.setCircle(160);const halo=this.add.circle(x,y,28,ph.gold,.13).setStrokeStyle(2,ph.gold,.95).setDepth(5);token.setData("halo",halo);this.tweens.add({targets:halo,scale:1.34,alpha:.38,duration:420,yoyo:true,repeat:-1});if(!this.turboTaught){this.turboTaught=true;this.setLesson("VICTORY TURBO // FASTER FLIGHT + FIRE, SHOT CAP UNCHANGED",3200)}}
 maybeDropBoom(x:number,y:number,kind:Kind){this.killsSinceBoom++;const chance={bat:.012,borer:.05,spore:.04,small:.003}[kind],guaranteed=this.killsSinceBoom>=24;if(!guaranteed&&this.rng.next()>chance)return;this.killsSinceBoom=0;const token=this.pickups.create(x,y,"boomToken") as Phaser.Physics.Arcade.Sprite;token.setDepth(6).setData("pickupType","boom").setData("spin",this.rng.range(-.22,.22)).setVelocity(this.rng.range(-16,16),62);if(!this.boomTaught){this.boomTaught=true;this.setLesson("$BOOM BLAST // CLEAR FIRE + STRIKE DIVERS",3000)}}
 updatePickups(delta:number){this.pickups.getChildren().forEach(o=>{const p=o as Phaser.Physics.Arcade.Sprite;if(!p.active)return;const halo=p.getData("halo");if(halo?.active)halo.setPosition(p.x,p.y).setAngle(-p.angle);p.angle+=p.getData("spin")*delta;if(p.y>635){halo?.destroy();p.destroy()}});this.enemies.getChildren().forEach(o=>{const e=o as Enemy;if(e.active&&e.kind==="small"&&(e.y>635||e.x<-40||e.x>520))e.destroy()})}
 collectPickup(pickup:Phaser.Physics.Arcade.Sprite){if(!pickup.active)return;pickup.getData("halo")?.destroy();const type=pickup.getData("pickupType");if(type==="weapon")this.collectWeaponCore(pickup);else if(type==="turbo")this.collectVictoryTurbo(pickup);else if(type==="boom")this.collectBoom(pickup);else this.collectGrowthSeed(pickup)}
 collectGrowthSeed(seed:Phaser.Physics.Arcade.Sprite){if(!seed.active)return;const value=seed.getData("growthValue")||5,x=seed.x,y=seed.y;seed.destroy();if(this.stage===4){this.run.score+=250;this.pickupBanner("GROWTH SEED\nSCORE +250",pc.green);this.setLesson("ANCIENT CANOPY // SEED BONUS +250",1200)}else{this.addGrowth(value);this.pickupBanner(`GROWTH SEED\n+${value} GROWTH`,pc.green);this.setLesson(`GROWTH SEED +${value}`,1050)}leafBurst(this,x,y,12);tone(this,470,.12,.07);this.updateHud()}
 collectWeaponCore(core:Phaser.Physics.Arcade.Sprite){if(!core.active)return;const {x,y}=core;core.destroy();if(this.weaponLevel===weaponLevels.length-1){this.run.score+=500;this.pickupBanner("WEAPON CORE\nSCORE +500",pc.gold);this.setLesson("MAX WEAPON // CORE BONUS +500",1400)}else{this.weaponLevel++;this.events.emit(E.WEAPON_UPGRADED,{level:this.weaponLevel});this.pickupBanner(`WEAPON CORE\n${weaponLevels[this.weaponLevel].name} ONLINE`,pc.gold);this.setLesson(`FIREPOWER ${this.weaponLevel+1}/5 // GROWTH UNCHANGED`,1900)}leafBurst(this,x,y,18);tone(this,690,.18,.08);this.updateHud()}
 collectVictoryTurbo(token:Phaser.Physics.Arcade.Sprite){if(!token.active)return;const {x,y}=token;token.destroy();this.turboUntil=this.time.now+tuning.turboMs;this.pickupBanner("VICTORY TURBO\n7 SECOND BOOST",pc.gold);this.setLesson("FASTER FLIGHT + FASTER SAP FIRE // SHOT CAP UNCHANGED",2400);leafBurst(this,x,y,22);tone(this,780,.2,.1)}
 collectBoom(token:Phaser.Physics.Arcade.Sprite){if(!token.active)return;const {x,y}=token;token.destroy();const divers=this.enemies.getChildren().filter(o=>(o as Enemy).active&&(o as Enemy).diving);this.bullets.clear(true,true);divers.forEach(o=>this.hitEnemy(o as Enemy,2,true));this.pickupBanner("$BOOM BLAST\nENEMY FIRE CLEARED",pc.gold);this.setLesson("$BOOM // SHOT WIPE + DIVING BLIGHT DAMAGED",2400);leafBurst(this,x,y,28);this.cameras.main.flash(120,255,145,35,false);tone(this,92,.28,.15);this.updateHud()}
 grow(){this.growth=0;this.stage++;this.run.maxStage=Math.max(this.run.maxStage,this.stage);this.applyStage();this.events.emit(E.PLAYER_GREW,{stage:this.stage});this.banner(`${stages[this.stage].name}\nARBORWING EXPANDED`,pc.green);leafBurst(this,this.player.x,this.player.y,26);tone(this,330,.18,.08);this.cameras.main.flash(180,60,190,80,false);if(!this.pruneTaught){this.pruneTaught=true;this.time.delayedCall(1900,()=>this.setLesson("GROWTH = SCORE + SHIELD RANGE + LARGER TARGET",3300))}}
 applyStage(announce=true){this.player.setTexture("playerSheet",this.stage).setScale(stages[this.stage].scale);this.player.body!.setSize(stages[this.stage].hit,26+this.stage*5);if(this.rescuedWing?.active)this.rescuedWing.setTexture("playerSheet",this.stage).setScale(stages[this.stage].scale).clearTint();this.stageText.setText(`GROWTH ${this.stage+1}/5 // ${stages[this.stage].name}  ×${stages[this.stage].mult.toFixed(2)}`);this.powerText.setText(`WEAPON ${this.weaponLevel+1}/5 // ${weaponLevels[this.weaponLevel].name}`);if(announce&&this.stage>1)this.setLesson(`${stages[this.stage].name} // STRONGER SHIELD · HIGHER SCORE`,1800)}
 prune(){if(this.paused||this.time.now<this.invulnUntil)return;if(this.stage===0){this.setLesson("TREE SHIELD NEEDS GROWTH // REACH SAPLING",1600);return}if(this.pruneCharge<tuning.pruneChargeMax){this.setLesson(`TREE SHIELD ${this.pruneCharge}% // DESTROY BLIGHT TO CHARGE`,1600);return}const old=this.stage;this.stage--;this.growth=0;this.pruneCharge=0;this.pruneReadyAnnounced=false;this.invulnUntil=this.time.now+tuning.pruneInvuln;this.pruneKills=0;this.applyStage(false);this.events.emit(E.PLAYER_PRUNED,{from:old,to:this.stage});this.cameras.main.shake(170,.014);this.cameras.main.flash(90,80,255,115,false);this.banner(`TREE SHIELD DEPLOYED\nDANGER CLEARED · GROWTH -1`,pc.gold);tone(this,105,.18,.18);
  const radius=150+old*24;this.bullets.getChildren().forEach(o=>{const b=o as Phaser.Physics.Arcade.Sprite;if(b.active&&Phaser.Math.Distance.Between(this.player.x,this.player.y,b.x,b.y)<radius+45){this.pruneKills++;this.run.score+=50;leafBurst(this,b.x,b.y,3);b.destroy()}});this.enemies.getChildren().map(o=>o as Enemy).filter(e=>e.active&&Phaser.Math.Distance.Between(this.player.x,this.player.y,e.x,e.y)<radius).sort((a,b)=>Phaser.Math.Distance.Between(this.player.x,this.player.y,a.x,a.y)-Phaser.Math.Distance.Between(this.player.x,this.player.y,b.x,b.y)).slice(0,3).forEach(e=>{e.setData("shieldStunUntil",this.time.now+450);this.hitEnemy(e,1,true)});const ring=this.add.circle(this.player.x,this.player.y,22,ph.green,.12).setStrokeStyle(6,ph.cyan,.9).setDepth(6);this.tweens.add({targets:ring,scale:radius/22,alpha:0,duration:360,ease:"Cubic.out",onComplete:()=>ring.destroy()});leafBurst(this,this.player.x,this.player.y,34);
  this.time.delayedCall(420,()=>this.scorePrune());this.time.delayedCall(900,()=>this.setLesson("SHIELDED // SMALLER + FASTER + PROTECTED",1900));this.updateHud();
 }
 scorePrune(){let label="",bonus=0;if(this.pruneKills>=8){label="PERFECT SHIELD";bonus=3000;this.run.perfect++;this.events.emit(E.PERFECT_PRUNE,{kills:this.pruneKills})}else if(this.pruneKills>=5){label="GREAT SHIELD";bonus=1200}else if(this.pruneKills>=3){label="GOOD SHIELD";bonus=500}else if(this.pruneKills===1){label="TIMELY SHIELD";bonus=250}if(label){this.run.score+=bonus;this.banner(`${label}\n${this.pruneKills} SHOTS · +${bonus.toLocaleString()}`,label.startsWith("PERFECT")?pc.gold:pc.green);tone(this,190,.35,.09)}this.updateHud()}
 damagePlayer(){if(this.invincible||this.time.now<this.invulnUntil)return;this.waveDamage=true;this.invulnUntil=this.time.now+tuning.damageInvuln;this.chain=0;this.events.emit(E.PLAYER_DAMAGED,{stage:this.stage});this.cameras.main.shake(250,.022);this.cameras.main.flash(140,240,55,70,false);tone(this,70,.25,.2);leafBurst(this,this.player.x,this.player.y,20);if(this.grafted&&this.rescuedWing?.active){this.rescuedWing.destroy();this.rescuedWing=undefined;this.grafted=false;this.banner("DUAL CANOPY BROKEN\nSINGLE FIGHTER REMAINS",pc.danger);this.setLesson("RESCUED WING LOST // FIREPOWER RETURNED TO NORMAL",1900);this.updateHud();return}if(this.stage>0){this.stage--;this.growth=0;this.applyStage(false);this.banner("STRUCTURAL BREAK\nWEAPON RETAINED",pc.danger)}else{this.lives--;const lostWeapon=this.weaponLevel>0;if(lostWeapon)this.weaponLevel--;this.applyStage(false);this.banner(lostWeapon?"SEEDLING LOST\nWEAPON -1":"SEEDLING LOST",pc.danger);if(this.lives<=0)this.endRun()}this.updateHud()}
 spawn(kind:Kind,pattern="leftArc"){
  const cfg=enemyConfig[kind],i=this.waveSpawned,row=Math.floor(i/8),column=i%8;
  const leader=!this.isCanopyRush()&&kind==="bat"&&row===0&&(column===3||(this.run.wave>=4&&column===4)),e=this.enemies.create(-35,-35,leader?"leader":kind) as Enemy;e.kind=kind;e.hp=leader?2:cfg.hp;e.homeX=54+column*53;e.homeY=112+row*42;e.phase=this.rng.range(0,Math.PI*2);e.diving=false;e.settled=false;e.returning=false;e.formationIndex=i;e.lastFire=0;e.setData("leader",leader).setData("formationRow",row).setData("mutateAt",this.run.wave>=2&&!leader&&kind==="bat"&&i%7===2?this.waveStart+this.rng.range(10500,14500):0).setData("motionDeadline",this.time.now+4800).setDepth(3).setScale(leader?1.18:kind==="borer"?1.15:1);if(this.isCanopyRush())this.rushTargets++;this.flyEntry(e,pattern);
 }
 flyEntry(e:Enemy,pattern:string){const fromRight=pattern==="rightArc"||(pattern==="cross"&&e.formationIndex%2===1),start=new Phaser.Math.Vector2(fromRight?520:-40,pattern==="sweep"?-25:80+(e.formationIndex%3)*28),c1=new Phaser.Math.Vector2(fromRight?370:110,pattern==="sweep"?15:230),c2=new Phaser.Math.Vector2(fromRight?465:15,pattern==="sweep"?280:340),end=new Phaser.Math.Vector2(e.homeX,e.homeY),curve=new Phaser.Curves.CubicBezier(start,c1,c2,end);e.setPosition(start.x,start.y);const duration=this.run.wave===0?3600:Math.max(1050,1500-this.run.wave*30);if(this.run.wave>=4&&!this.isCanopyRush())this.time.delayedCall(Math.round(duration*.62),()=>e.active&&this.player.active&&this.enemyFire(e));this.tweens.addCounter({from:0,to:1,duration,ease:"Sine.inOut",onUpdate:t=>{if(e.active){const value=t.getValue()??0,p=curve.getPoint(value);e.setPosition(p.x,p.y);e.setAngle(Math.sin(value*Math.PI*2)*(fromRight?-18:18))}},onComplete:()=>{if(e.active){e.setAngle(0);e.settled=true;e.setPosition(e.homeX,e.homeY)}}})}
 updateEnemies(time:number,delta:number){const drift=Math.sin((time-this.waveStart)*.00105)*18,bob=Math.sin((time-this.waveStart)*.0018)*3;this.enemies.getChildren().forEach(o=>{const e=o as Enemy;if(!e.active)return;e.phase+=delta*.001;const stunned=time<(e.getData("shieldStunUntil")||0);if(stunned){e.setTint(0x9dffb4);return}else if(!e.getData("transformed"))e.clearTint();const mutateAt=e.getData("mutateAt")||0;if(mutateAt&&time>=mutateAt&&!e.getData("transformed")&&e.settled){e.setData("transformed",true).setData("mutateAt",0).setTexture("wasp").setScale(1.12);e.hp++;leafBurst(this,e.x,e.y,12);this.setLesson("BLIGHT BAT MUTATED // NEW ATTACK PATTERN",1500);tone(this,180,.18,.05)}const deadline=e.getData("motionDeadline")||0;if(!e.settled&&deadline&&time>deadline){e.diving=false;e.returning=false;e.settled=true;e.setAngle(0).setPosition(e.homeX+drift,e.homeY+bob);e.setData("motionDeadline",0)}if(e.settled&&!e.diving&&!e.returning){e.x=e.homeX+drift;e.y=e.homeY+bob+Math.sin(e.phase)*1.5}});if(!this.isCanopyRush()&&time>=this.nextDiveAt)this.beginFormationDive(time);if(this.run.wave>0&&!this.isCanopyRush()&&time>=this.nextEnemyFireAt)this.formationFire(time);if(this.run.wave===2&&!this.captureUsed&&time>this.waveStart+9800)this.beginRootSnare()}
 beginFormationDive(time:number){const maxDivers=Math.min(4,1+Math.floor(this.run.wave/2)),divers=this.enemies.getChildren().filter(o=>(o as Enemy).active&&(o as Enemy).diving).length;if(divers>=maxDivers){this.nextDiveAt=time+350;return}const candidates=this.enemies.getChildren().map(o=>o as Enemy).filter(e=>e.active&&e.settled&&!e.diving&&!e.returning&&!e.getData("isCaptor")&&time>=(e.getData("shieldStunUntil")||0)&&e.kind!=="spore"&&e.kind!=="small");if(!candidates.length){this.nextDiveAt=time+450;return}const leaders=candidates.filter(e=>e.getData("leader")),e=leaders.length&&this.rng.next()<.58?leaders[this.rng.int(leaders.length)]:candidates[this.rng.int(candidates.length)],pack=[e],sameRow=candidates.filter(x=>x!==e&&!x.getData("leader")&&x.getData("formationRow")===e.getData("formationRow")).sort((a,b)=>Math.abs(a.homeX-e.homeX)-Math.abs(b.homeX-e.homeX));if(e.getData("leader"))pack.push(...sameRow.slice(0,2));else{const roll=this.rng.next(),extra=this.run.wave>=4&&roll<.28?2:this.run.wave>=1&&roll<.5?1:0;pack.push(...sameRow.slice(0,extra))}const attackId=pack.length>1?++this.attackSerial:0;if(attackId)this.escortTargets.set(attackId,pack.length);pack.forEach((unit,i)=>this.primeDive(unit,time+i*125,attackId));const aliveRatio=this.enemies.countActive()/Math.max(1,this.waveData().spawns.length),pace=.48+.52*aliveRatio,baseLow=this.run.wave===0?2100:this.run.wave===1?1650:1150,baseHigh=this.run.wave===0?3600:this.run.wave===1?2200:1700;this.nextDiveAt=time+this.rng.range(baseLow,baseHigh)*pace}
 primeDive(e:Enemy,at:number,attackId=0){e.diving=true;e.settled=false;e.setData("motionDeadline",at+4300).setData("escortAttack",attackId).setTint(0xffe06b);this.time.delayedCall(Math.max(0,at-this.time.now),()=>{if(!e.active)return;this.tweens.add({targets:e,scaleX:e.scaleX*1.15,scaleY:e.scaleY*1.15,duration:140,yoyo:true,onComplete:()=>this.time.delayedCall(100,()=>this.executeDive(e))})})}
 executeDive(e:Enemy){if(!e.active)return;e.clearTint();const start=new Phaser.Math.Vector2(e.x,e.y),targetX=Phaser.Math.Clamp(this.player.x+this.rng.range(-45,45),28,452),side=e.x<240?-1:1,c1=new Phaser.Math.Vector2(e.x+side*85,e.y+80),c2=new Phaser.Math.Vector2(targetX-side*110,470),end=new Phaser.Math.Vector2(targetX,760),curve=new Phaser.Curves.CubicBezier(start,c1,c2,end),duration=e.getData("transformed")?1050:e.kind==="borer"?1200:Math.max(1120,1550-this.run.wave*32);this.time.delayedCall(Math.round(duration*.5),()=>e.active&&e.diving&&this.player.active&&this.enemyFire(e));if(this.run.wave>=4||e.getData("transformed"))this.time.delayedCall(Math.round(duration*.72),()=>e.active&&e.diving&&this.player.active&&this.enemyFire(e));this.tweens.addCounter({from:0,to:1,duration,ease:"Sine.in",onUpdate:t=>{if(e.active){const value=t.getValue()??0,p=curve.getPoint(value);e.setPosition(p.x,p.y);e.setAngle(side*(18+70*value))}},onComplete:()=>this.returnToFormation(e)})}
 returnToFormation(e:Enemy){if(!e.active)return;e.returning=true;e.diving=false;e.setData("rescueWindow",false).setData("motionDeadline",this.time.now+1800).setAngle(0).setPosition(e.homeX,-35);this.tweens.add({targets:e,y:e.homeY,duration:900,ease:"Sine.out",onComplete:()=>{if(e.active){e.returning=false;e.settled=true;e.setData("motionDeadline",0);if(e.getData("isCaptor")&&e.getData("holding"))this.scheduleCaptorRaid(e)}}})}
 formationFire(time:number){const candidates=this.enemies.getChildren().map(o=>o as Enemy).filter(e=>e.active&&e.settled&&!e.diving&&!e.returning&&!e.getData("isCaptor")&&time>=(e.getData("shieldStunUntil")||0)&&e.kind!=="small");if(candidates.length){const volleys=this.run.wave>=5&&this.rng.next()<.35?2:1;for(let i=0;i<volleys;i++){const e=candidates[this.rng.int(candidates.length)];this.enemyFire(e);e.lastFire=time}}const aliveRatio=this.enemies.countActive()/Math.max(1,this.waveData().spawns.length),pace=.5+.5*aliveRatio,low=this.run.wave===0?1750:this.run.wave===1?1100:Math.max(540,780-this.run.wave*18),high=this.run.wave===0?2450:this.run.wave===1?1650:Math.max(850,1250-this.run.wave*22);this.nextEnemyFireAt=time+this.rng.range(low,high)*pace}
 beginRootSnare(){this.captureUsed=true;const homeX=this.player.x<240?420:60,e=this.enemies.create(homeX,-55,"rootCaptor") as Enemy;e.kind="borer";e.hp=6;e.homeX=homeX;e.homeY=105;e.phase=0;e.diving=true;e.settled=false;e.returning=false;e.formationIndex=-2;e.lastFire=0;e.setData("isCaptor",true).setData("formationRow",-1).setData("motionDeadline",this.time.now+5200).setDepth(5).setScale(1.12);this.snareEnemy=e;this.banner("ROOT CAPTOR DESCENDING",pc.danger);this.setLesson("CAPTOR CRAFT IS ALIGNING A ROOT BEAM",2600);this.tweens.add({targets:e,x:this.player.x,y:245,duration:1150,ease:"Sine.inOut",onComplete:()=>{if(!e.active)return;e.diving=false;const h=350;this.snareBeam=this.add.rectangle(e.x,e.y+24+h/2,72,h,0x65dc79,.2).setStrokeStyle(4,0xf2c94c,.95).setDepth(2);this.tweens.add({targets:this.snareBeam,alpha:{from:.12,to:.46},duration:160,yoyo:true,repeat:12});e.setData("snareUntil",this.time.now+3100);this.setLesson("MOVE OUTSIDE THE GOLD ROOT BEAM",2800)}})}
 updateCapture(time:number){if(this.rescuedWing?.active&&this.player.active){const offset=54+this.stage*5;if(this.player.x+offset*this.wingSide>455||this.player.x+offset*this.wingSide<25)this.wingSide*=-1;this.rescuedWing.setPosition(this.player.x+offset*this.wingSide,this.player.y).setAngle(0)}if(this.capturedWing?.active&&this.snareEnemy?.active)this.capturedWing.setPosition(this.snareEnemy.x,this.snareEnemy.y+45).setAngle(this.snareEnemy.angle);const e=this.snareEnemy;if(!e?.active||!this.snareBeam?.active)return;this.snareBeam.x=e.x;const until=e.getData("snareUntil")||0;if(this.player.active&&time<until&&Math.abs(this.player.x-e.x)<36&&this.player.y>e.y)this.capturePlayer(e);else if(until&&time>=until){this.snareBeam.destroy();this.snareBeam=undefined;this.snareEnemy=undefined;e.setData("isCaptor",false);this.returnToFormation(e);this.setLesson("ROOT SNARE EVADED",1400)}}
 capturePlayer(e:Enemy){if(!this.player.active)return;this.waveDamage=true;this.snareBeam?.destroy();this.snareBeam=undefined;this.capturedStage=this.stage;e.setData("holding",true).setData("corruptionHits",0);this.capturedWing=this.physics.add.sprite(e.x,e.y+45,"playerSheet",this.stage).setDepth(4).setScale(stages[this.stage].scale).setTint(0xc06cff);this.lives--;if(this.weaponLevel>0)this.weaponLevel--;this.player.setActive(false).setVisible(false);this.player.body!.enable=false;this.banner("ARBORWING CAPTURED",pc.danger);this.setLesson("CAPTOR WILL ATTACK // STRIKE DURING GOLD RESCUE WINDOW",3100);tone(this,72,.45,.16);this.updateHud();this.tweens.add({targets:e,y:-55,duration:600,ease:"Sine.in",onComplete:()=>this.returnToFormation(e)});if(this.lives<=0){this.time.delayedCall(750,()=>this.endRun());return}this.time.delayedCall(900,()=>{this.stage=0;this.growth=0;this.pruneCharge=0;this.applyStage(false);this.player.setPosition(240,570).setActive(true).setVisible(true);this.player.body!.enable=true;this.invulnUntil=this.time.now+1600;this.banner("RESERVE SEEDLING DEPLOYED",pc.green);this.updateHud()})}
 scheduleCaptorRaid(e:Enemy){if(e.getData("raidScheduled"))return;e.setData("raidScheduled",true);this.time.delayedCall(1850,()=>{e.setData("raidScheduled",false);if(e.active&&e.getData("holding")&&this.capturedWing?.active)this.captorRaid(e)})}
 captorRaid(e:Enemy){if(!e.active)return;e.settled=false;e.diving=true;e.setData("rescueWindow",true).setData("motionDeadline",this.time.now+3600).setTint(0xffe06b);this.banner("RESCUE WINDOW OPEN",pc.gold);this.setLesson("ATTACK THE CAPTOR DURING ITS DIVE",2100);const targetX=Phaser.Math.Clamp(this.player.x+this.rng.range(-55,55),60,420);this.time.delayedCall(520,()=>e.active&&this.enemyFire(e));this.time.delayedCall(820,()=>e.active&&this.enemyFire(e));this.tweens.add({targets:e,x:targetX,y:405,angle:e.x<240?38:-38,duration:1050,ease:"Sine.in",onComplete:()=>this.returnToFormation(e)})}
 corruptCapturedWing(e:Enemy){const now=this.time.now,last=e.getData("lastCorruptAt")||0;if(now-last<700)return;e.setData("lastCorruptAt",now);const hits=(e.getData("corruptionHits")||0)+1;e.setData("corruptionHits",hits);this.setLesson(hits<3?`CAPTIVE SHIELD HIT ${hits}/3 // WAIT FOR THE DIVE`:"CAPTURED ARBORWING CORRUPTED",1800);tone(this,95,.18,.08);if(hits<3)return;const x=e.x,y=e.y+45;this.capturedWing?.destroy();this.capturedWing=undefined;e.setData("holding",false);this.snareEnemy=undefined;const c=this.enemies.create(x,y,"playerSheet",this.capturedStage) as Enemy;c.kind="borer";c.hp=3;c.homeX=240;c.homeY=140;c.phase=0;c.diving=true;c.settled=false;c.returning=false;c.formationIndex=-3;c.lastFire=0;c.setData("corrupted",true).setData("formationRow",-1).setData("motionDeadline",now+4200).setDepth(4).setScale(stages[this.capturedStage].scale).setTint(0xff4fc8);this.banner("ARBORWING CORRUPTED",pc.danger);this.executeDive(c)}
 rescueCapturedWing(e:Enemy){if(e!==this.snareEnemy||!this.capturedWing?.active||!e.getData("rescueWindow"))return;this.capturedWing.destroy();this.capturedWing=undefined;this.snareBeam?.destroy();this.snareBeam=undefined;this.snareEnemy=undefined;e.setData("holding",false);this.grafted=true;this.wingSide=this.player.x>240?-1:1;this.rescuedWing=this.add.sprite(this.player.x+(54+this.stage*5)*this.wingSide,this.player.y,"playerSheet",this.stage).setDepth(4).setScale(this.player.scaleX,this.player.scaleY);this.banner("FULL-SIZE ARBORWING RESCUED\nDUAL CANOPY ONLINE",pc.gold);this.setLesson("MATCHED WINGS // BOTH FIRE TOGETHER",2800);this.run.score+=2500;leafBurst(this,e.x,e.y,34);tone(this,410,.32,.1)}
 enemyFire(e:Enemy){
  const error=this.run.wave===0?this.rng.range(-.2,.2):this.run.wave===1?this.rng.range(-.1,.1):this.rng.range(-.045,.045),aim=Phaser.Math.Angle.Between(e.x,e.y,this.player.x,this.player.y)+error,p=tuning.enemyProjectiles,speedScale=1+Math.min(this.run.wave,12)*.035;tone(this,e.kind==="borer"?175:e.kind==="spore"?280:350,.07,.03);
  if(e.getData("isCaptor")){
   [-.2,0,.2].forEach(offset=>this.launchHostile(e.x,e.y+22,"barkDrill",aim+offset,(p.drillSpeed+18)*speedScale,"drill"));
  }else if(e.getData("transformed")){
   [-.16,0,.16].forEach(offset=>this.launchHostile(e.x,e.y+13,"blightDart",aim+offset,(p.dartSpeed+20)*speedScale,"dart"));
  }else if(e.kind==="borer"){
   this.launchHostile(e.x-5,e.y+15,"barkDrill",aim-.12,p.drillSpeed*speedScale,"drill");
   this.launchHostile(e.x+5,e.y+15,"barkDrill",aim+.12,p.drillSpeed*speedScale,"drill");
  }else if(e.kind==="spore"){
   this.launchHostile(e.x,e.y+15,"sporeSeed",aim,p.sporeSpeed*speedScale,"spore");
  }else this.launchHostile(e.x,e.y+13,"blightDart",aim,p.dartSpeed*speedScale,"dart");
 }
 launchHostile(x:number,y:number,texture:string,angle:number,speed:number,kind:string){const b=this.bullets.create(x,y,texture) as Phaser.Physics.Arcade.Sprite;b.setVelocity(Math.cos(angle)*speed,Math.sin(angle)*speed).setDepth(3).setCollideWorldBounds(true).setData("hostile",true).setData("projectileKind",kind).setData("baseVx",Math.cos(angle)*speed).setData("wobblePhase",this.rng.range(0,Math.PI*2));(b.body as Phaser.Physics.Arcade.Body).onWorldBounds=true}
 updateHostileBullets(time:number,delta:number){this.bullets.getChildren().forEach(o=>{const b=o as Phaser.Physics.Arcade.Sprite;if(!b.active)return;const kind=b.getData("projectileKind");if(kind==="drill")b.angle+=delta*.42;else if(kind==="dart")b.angle+=delta*.16;else if(kind==="spore")b.setVelocityX((b.getData("baseVx")||0)+Math.sin(time*.008+(b.getData("wobblePhase")||0))*tuning.enemyProjectiles.sporeWobble)})}
 hitEnemy(e:Enemy,damage:number,prune:boolean){if(!e.active)return;if(e===this.snareEnemy&&e.getData("holding")&&!e.getData("rescueWindow")&&!prune){this.corruptCapturedWing(e);return}e.hp-=damage;e.setTintFill(0xffffff);this.time.delayedCall(55,()=>e.active&&e.clearTint());if(e.hp>0){if(e.getData("leader"))e.setTexture("leaderCracked");tone(this,150,.03,.03);return}const {x,y,kind}=e,row=e.getData("formationRow") as number,attackId=e.getData("escortAttack") as number,isLeader=!!e.getData("leader"),wasDiving=e.diving;if(this.isCanopyRush()&&e.formationIndex>=0)this.rushDestroyed++;if(attackId){const kills=(this.escortKills.get(attackId)||0)+1,target=this.escortTargets.get(attackId)||0;this.escortKills.set(attackId,kills);if(kills===target){this.run.score+=target>=3?2500:1200;this.banner(target>=3?"CONVOY BREAK\n+2,500":"CONVOY BREAK\n+1,200",pc.gold)}}this.rescueCapturedWing(e);if(e===this.snareEnemy){this.snareBeam?.destroy();this.snareBeam=undefined;this.snareEnemy=undefined}e.destroy();const cfg=enemyConfig[kind],baseScore=isLeader?300:cfg.score,attackScore=wasDiving?2:1;const chainMult=this.chain>=100?2.5:this.chain>=50?2:this.chain>=25?1.5:this.chain>=10?1.25:this.chain>=5?1.1:1;this.run.score+=Math.round(baseScore*attackScore*stages[this.stage].mult*chainMult);this.run.kills++;this.chain++;this.chainUntil=this.time.now+tuning.chainMs;if(row>=0&&!this.clearedRows.has(row)){const rowAlive=this.enemies.getChildren().some(o=>{const other=o as Enemy;return other.active&&other.getData("formationRow")===row});if(!rowAlive){this.clearedRows.add(row);this.run.score+=500;this.banner("FORMATION ROW\n+500",pc.green)}}if(!prune){const previousCharge=this.pruneCharge;this.pruneCharge=Math.min(tuning.pruneChargeMax,this.pruneCharge+cfg.pruneCharge);if(previousCharge<tuning.pruneChargeMax&&this.pruneCharge===tuning.pruneChargeMax&&!this.pruneReadyAnnounced){this.pruneReadyAnnounced=true;this.setLesson(this.stage>0?"TREE SHIELD READY // CLEAR DANGER · GROWTH -1":"TREE SHIELD CHARGED // GROW FIRST",3300);tone(this,420,.12,.06)}}this.maybeDropGrowthSeed(x,y,kind);if(!prune){this.maybeDropWeaponCore(x,y,kind);this.maybeDropVictoryTurbo(x,y,kind);this.maybeDropBoom(x,y,kind)}this.events.emit(E.ENEMY_KILLED,{kind,prune});leafBurst(this,x,y,kind==="borer"?16:9);tone(this,kind==="borer"?90:230,.06,.06);if(kind==="spore")for(let i=0;i<3;i++){const s=this.enemies.create(x,y,"small") as Enemy;s.kind="small";s.hp=1;s.homeX=x;s.homeY=y;s.phase=i*2;s.diving=true;s.settled=false;s.returning=false;s.formationIndex=-1;s.lastFire=999999;s.setVelocity((i-1)*75,90)}this.updateHud()}
 waveData(i=this.run.wave){return waves[(i+1)%4===0?3:Math.min(i,2)]}
 isCanopyRush(){return (this.run.wave+1)%4===0}
 startWave(i:number){this.run.wave=i;this.waveStart=this.time.now;this.waveSpawned=0;this.waveKillsStart=this.run.kills;this.waveClearing=false;this.waveDamage=false;this.clearedRows.clear();this.escortKills.clear();this.escortTargets.clear();this.rushTargets=0;this.rushDestroyed=0;this.rushShotsFired=0;this.rushShotsHit=0;this.nextDiveAt=this.waveStart+(i===0?15500:6500);this.nextEnemyFireAt=this.waveStart+(i===0?999999:5600);const w=this.waveData(i),n=String(i+1).padStart(2,"0");this.waveText.setText(`WAVE\n${n}`);this.badgeText.setText("◆ ".repeat(Math.min(i+1,8)).trim());this.banner(`${this.isCanopyRush()?"BONUS ":""}WAVE ${n}\n${w.name}`,this.isCanopyRush()?pc.green:pc.gold);this.events.emit(E.WAVE_STARTED,{wave:i+1});tone(this,this.isCanopyRush()?390:260,.22,.06)}
 updateWaves(time:number){const w=this.waveData();while(this.waveSpawned<w.spawns.length&&time-this.waveStart>=w.spawns[this.waveSpawned].delay){const s=w.spawns[this.waveSpawned];this.spawn(s.type as Kind,s.pattern);this.waveSpawned++}if(this.waveSpawned===w.spawns.length&&this.enemies.countActive()===0&&this.pickups.countActive()===0&&!this.waveClearing){this.clearTouchState();this.roundSequence()}}
 roundSequence(){this.waveClearing=true;this.bullets.clear(true,true);const number=this.run.wave+1,rush=this.isCanopyRush(),rate=Math.round(this.rushDestroyed/Math.max(1,this.rushTargets)*100),accuracy=Math.round(this.rushShotsHit/Math.max(1,this.rushShotsFired)*100),bonus=rush?(rate===100&&accuracy===100?10000:rate>=90&&accuracy>=85?3000:accuracy>=70?1500:0):0;if(bonus)this.run.score+=bonus;const next=this.waveData(this.run.wave+1).name,panel=this.add.rectangle(240,350,402,rush?282:224,ph.panel,.99).setStrokeStyle(3,rush?ph.green:ph.gold),title=this.add.text(240,rush?242:282,`${rush?"CANOPY RUSH":"CANOPY"} ${String(number).padStart(2,"0")} SECURED`,font(18,rush?pc.green:pc.gold)).setOrigin(.5),rushLine=`TARGET CLEAR  ${String(rate).padStart(3," ")}%\nSHOTS / HITS ${this.rushShotsFired} / ${this.rushShotsHit}\nACCURACY      ${String(accuracy).padStart(3," ")}%${bonus?`\nRUSH BONUS   +${bonus.toLocaleString()}`:""}`,body=this.add.text(240,rush?286:330,`BLIGHT CLEARED  ${this.run.kills-this.waveKillsStart}\n${rush?rushLine:`CHAIN          ${this.chain}`}\n\nNEXT // ${next}`,font(13,pc.text)).setOrigin(.5,0).setAlign("center").setLineSpacing(rush?6:8),card=this.add.container(0,0,[panel,title,body]).setDepth(25).setAlpha(0);this.tweens.add({targets:card,alpha:1,duration:220});tone(this,520,.25,.08);this.time.delayedCall(rush?3000:2400,()=>{card.destroy(true);this.startWave(this.run.wave+1)})}
 endRun(cleared=false){this.clearTouchState();this.run.score=Math.round(this.run.score);this.events.emit(E.RUN_ENDED,{...this.run,end:Date.now(),cleared});this.scene.start("gameover",{run:this.run,cleared})}
 updateHud(){this.scoreText.setText(`SCORE\n${String(this.run?.score||0).padStart(6,"0")}`);const cm=this.chain>=100?2.5:this.chain>=50?2:this.chain>=25?1.5:this.chain>=10?1.25:this.chain>=5?1.1:1;this.chainText.setText(`CHAIN ${this.chain}  ×${cm.toFixed(2)}`);this.livesText.setText("♠ ".repeat(Math.max(0,this.lives)).trim());this.stageText?.setText(`GROWTH ${this.stage+1}/5 // ${stages[this.stage].name}  ×${stages[this.stage].mult.toFixed(2)}`);this.powerText?.setText(`WEAPON ${this.weaponLevel+1}/5 // ${weaponLevels[this.weaponLevel].name}`);const need=stages[this.stage].need,ready=this.pruneCharge>=tuning.pruneChargeMax;this.growthText.setText(this.stage===4?"GROWTH MAX":`GROW ${this.growth} / ${need}`);this.pruneChargeText?.setText("");this.pruneText?.setText(this.stage===0?"GROW FIRST":ready?"READY -1 GROW":`SHIELD ${this.pruneCharge}%`).setColor(ready?pc.gold:pc.green);this.pruneButtonBg?.setStrokeStyle(2,ready&&this.stage>0?ph.gold:ph.cyan)}
 setLesson(message:string,duration=1800){this.lessonText?.setText(message).setAlpha(1);this.tweens.killTweensOf(this.lessonText);this.tweens.add({targets:this.lessonText,alpha:0,delay:duration,duration:300})}
 showPruneGuide(first=false){if(this.debugPanel.visible)return;this.paused=true;this.physics.world.isPaused=true;const pieces:Phaser.GameObjects.GameObject[]=[];const shade=this.add.rectangle(240,360,480,720,ph.bg,.9).setInteractive();const panel=this.add.rectangle(240,352,438,500,ph.panel,.99).setStrokeStyle(3,ph.cyan);const title=this.add.text(240,112,first?"TREE SHIELD READY":"TREE FORCE FIELD GUIDE",font(17,pc.green)).setOrigin(.5);const body=this.add.text(240,147,"FIRE // LEFT CLICK, Z, X, OR THE FIRE BUTTON.\nONLY A FEW SAP SHOTS MAY FLY AT ONCE.\nHOLDING FIRE REPEATS MORE SLOWLY.\nAUTO // TOGGLE ON FOR SLOW, CAPPED FIRE.\n\nWEAPON CORES ADD SPEED, TWIN PODS,\nPIERCING, OR DAMAGE — NEVER SCREEN-WIDE SPREAD.\nGROWTH SEEDS EXPAND THE ARBORWING FOR\nMORE SCORE AND SHIELD RANGE, BUT ADD RISK.\n\nDESTROY DIVING ENEMIES FOR DOUBLE SCORE.\nBREAK A FULL ESCORT CONVOY FOR A BONUS.\nA RESCUED ARBORWING DOUBLES FIREPOWER,\nBUT THE COMPANION IS LOST ON THE NEXT HIT.\n\nTREE SHIELD // EMERGENCY DEFENSE\nCLEARS NEARBY SHOTS, STUNS UP TO 3 ENEMIES,\nGRANTS BRIEF PROTECTION, AND COSTS 1 GROWTH.\nWEAPON LEVEL IS PRESERVED.\n\nCANOPY RUSH SCORES TARGETS AND ACCURACY.",font(11,pc.text)).setOrigin(.5,0).setAlign("center").setLineSpacing(3);const button=this.add.rectangle(240,584,246,48,ph.bgSoft).setStrokeStyle(2,ph.gold).setInteractive();const bt=this.add.text(240,584,"BACK TO THE CANOPY",font(12,pc.gold)).setOrigin(.5);const close=()=>{guide.destroy(true);this.paused=false;this.physics.world.isPaused=false};button.on("pointerdown",close);shade.on("pointerdown",()=>{});pieces.push(shade,panel,title,body,button,bt);const guide=this.add.container(0,0,pieces).setDepth(40)}
 drawMeters(){const need=stages[this.stage].need,growthP=this.stage===4?1:this.growth/need,pruneP=this.pruneCharge/tuning.pruneChargeMax;this.children.getByName("growthFill")?.destroy();this.children.getByName("pruneFill")?.destroy();this.add.rectangle(12,709,92*growthP,5,ph.green).setOrigin(0,.5).setDepth(12).setName("growthFill");this.add.rectangle(215,710,104*pruneP,4,this.pruneCharge>=tuning.pruneChargeMax?ph.gold:ph.cyan).setOrigin(0,.5).setDepth(13).setName("pruneFill")}
 banner(t:string,c:string){this.notice.setVisible(true).setText(t).setColor(c).setAlpha(1).setScale(.65);this.tweens.killTweensOf(this.notice);this.tweens.add({targets:this.notice,scale:1,alpha:{from:1,to:0},duration:950,hold:350,ease:"Back.out",onComplete:()=>this.notice.setVisible(false).setText("")})}
 pickupBanner(t:string,c:string){this.pickupText.setVisible(true).setText(t).setColor(c).setAlpha(1).setScale(.65);this.tweens.killTweensOf(this.pickupText);this.tweens.add({targets:this.pickupText,scale:1,alpha:{from:1,to:0},duration:1050,hold:700,ease:"Back.out",onComplete:()=>this.pickupText.setVisible(false).setText("")})}
 autoPause(){if(!this.paused)this.togglePause()}
 togglePause(){this.paused=!this.paused;this.physics.world.isPaused=this.paused;this.notice.setVisible(this.paused).setAlpha(1).setScale(1).setText(this.paused?"CANOPY PAUSED\nPRESS ESC":"");if(!this.paused)this.notice.setText("")}
 makeDebug(){const bg=this.add.rectangle(240,380,360,440,ph.panel,.98).setStrokeStyle(2,ph.cyan);const title=this.add.text(240,174,"TREE FORCE LAB",font(16,pc.green)).setOrigin(.5);const buttons:Phaser.GameObjects.GameObject[]=[bg,title];const opts:[string,()=>void][]=[["STAGE +",()=>{this.stage=(this.stage+1)%5;this.applyStage();this.updateHud()}],["WEAPON +",()=>{this.weaponLevel=(this.weaponLevel+1)%5;this.updateHud()}],["+10 GROWTH",()=>this.addGrowth(10)],["FORCE SHIELD",()=>{this.pruneCharge=tuning.pruneChargeMax;this.prune()}],["INVINCIBLE",()=>this.invincible=!this.invincible],["SPAWN BAT",()=>this.spawn("bat")],["SPAWN BORER",()=>this.spawn("borer")],["SPAWN SPORE",()=>this.spawn("spore")],["KILL ALL",()=>this.enemies.clear(true,true)],["RESTART WAVE",()=>{this.enemies.clear(true,true);this.startWave(this.run.wave)}],["HITBOXES",()=>{this.hitboxes=!this.hitboxes;this.physics.world.drawDebug=this.hitboxes}],["SHOW FPS",()=>this.showFps=!this.showFps],["COORDS",()=>this.coords=!this.coords],["SPEED .5/1X",()=>this.time.timeScale=this.time.timeScale===1?.5:1]];opts.forEach(([label,fn],i)=>{const x=155+(i%2)*170,y=215+Math.floor(i/2)*44;const r=this.add.rectangle(x,y,148,32,ph.bgSoft).setStrokeStyle(1,ph.cyan).setInteractive();const t=this.add.text(x,y,label,font(9)).setOrigin(.5);r.on("pointerdown",fn);buttons.push(r,t)});this.debugPanel=this.add.container(0,0,buttons).setDepth(30).setVisible(false)}
}

class GameOverScene extends Phaser.Scene{
 constructor(){super("gameover")}create(data:{run:RunState;cleared:boolean}){forest(this);const accuracy=Math.round(data.run.shotsHit/Math.max(1,data.run.shotsFired)*100);this.add.rectangle(240,360,480,720,ph.bg,.82);this.add.text(240,120,data.cleared?"CANOPY SECURED":"THE CANOPY\nHAS FALLEN",font(29,data.cleared?pc.green:pc.danger)).setOrigin(.5).setAlign("center");this.add.text(240,232,`SCORE           ${data.run.score.toLocaleString()}\nWAVE            ${data.run.wave+1}\nBLIGHT DOWN     ${data.run.kills}\nSHOTS / HITS    ${data.run.shotsFired} / ${data.run.shotsHit}\nACCURACY        ${accuracy}%\nPERFECT SHIELDS ${data.run.perfect}\nMAX GROWTH      ${stages[data.run.maxStage].name}`,font(13)).setOrigin(.5,0).setLineSpacing(10);const b=this.add.rectangle(240,518,220,54,ph.bgSoft).setStrokeStyle(3,ph.cyan).setInteractive();this.add.text(240,518,"PLAY AGAIN",font(16,pc.gold)).setOrigin(.5);b.on("pointerdown",()=>this.scene.start("game"));this.input.keyboard?.once("keydown-SPACE",()=>this.scene.start("game"));this.add.text(240,600,`RUN ${data.run.runId}\nSEED ${data.run.seed} · v${GAME_VERSION}`,font(8,pc.muted)).setOrigin(.5).setAlign("center")}}

function makeTextures(s:Phaser.Scene){
 const g=s.make.graphics({x:0,y:0},false);const tex=(key:string,w:number,h:number,draw:()=>void)=>{g.clear();draw();g.generateTexture(key,w,h)};
 tex("sap",6,14,()=>{g.fillStyle(ph.green).fillRect(2,0,2,12);g.fillStyle(ph.text).fillRect(2,0,2,3)});
 tex("blightDart",16,16,()=>{g.fillStyle(0x26050d).fillCircle(8,8,8);g.lineStyle(2,0xff476f).strokeCircle(8,8,7);g.fillStyle(0xa91945).fillCircle(8,8,5);g.fillStyle(0x300713).fillRect(7,3,2,10).fillRect(5,3,4,2).fillRect(5,7,4,2).fillRect(5,11,4,2);g.fillStyle(0xffd2df).fillTriangle(10,4,13,8,10,12)});
 tex("barkDrill",18,18,()=>{g.fillStyle(0x311505).fillCircle(9,9,9);g.lineStyle(2,0xffa52e).strokeCircle(9,9,8);g.fillStyle(0xc56720).fillCircle(9,9,6);g.lineStyle(2,0xffe28a).strokeCircle(9,9,3);g.lineStyle(2,0x4a1c06).beginPath().moveTo(9,1).lineTo(9,17).moveTo(1,9).lineTo(17,9).strokePath();g.fillStyle(0xffe28a).fillCircle(9,9,1)});
 tex("sporeSeed",18,18,()=>{g.fillStyle(0x251036).fillCircle(9,9,9);g.lineStyle(2,0xb04bd2).strokeCircle(9,9,8);g.fillStyle(0x613276).fillCircle(9,9,6);g.fillStyle(0xffe06b).fillCircle(9,7,3);g.fillStyle(0xd9ff8a).fillCircle(6,5,1.5).fillCircle(12,11,1.5);g.fillStyle(0x341440).fillTriangle(9,12,5,16,13,16)});
 tex("growthSeed",15,19,()=>{g.fillStyle(0x173f24).fillEllipse(7,10,13,17);g.lineStyle(2,ph.gold).strokeEllipse(7,10,13,17);g.fillStyle(ph.green).fillEllipse(7,10,7,12);g.fillStyle(0xf8ffb0).fillCircle(6,6,2);g.fillStyle(ph.gold).fillRect(6,0,2,5)});
 tex("weaponCore",19,19,()=>{g.fillStyle(0x22103f).fillCircle(9,9,9);g.lineStyle(2,ph.gold).strokeCircle(9,9,8);g.fillStyle(ph.cyan).fillCircle(9,9,5);g.fillStyle(0xffffff).fillRect(8,3,2,12).fillRect(3,8,12,2)});
 tex("boomToken",26,26,()=>{g.fillStyle(0x4b1204).fillCircle(13,13,13);g.lineStyle(2,0xffe06b).strokeCircle(13,13,12);g.fillStyle(0xff6a00).fillCircle(13,13,9);g.fillStyle(0xffd83d).fillTriangle(13,2,16,11,24,13).fillTriangle(24,13,16,16,13,24).fillTriangle(13,24,10,16,2,13).fillTriangle(2,13,10,10,13,2);g.fillStyle(0xffffff).fillCircle(13,13,3)});
 tex("branch",8,30,()=>{g.fillStyle(0x9a5725).fillRect(3,0,3,27);g.fillStyle(ph.green).fillTriangle(3,7,0,3,1,11).fillTriangle(6,15,8,11,7,20)});
 tex("bat",30,22,()=>{g.fillStyle(0x6b2485).fillTriangle(15,10,0,2,7,18).fillTriangle(15,10,30,2,23,18);g.fillStyle(0xc55df0).fillCircle(15,10,6);g.fillStyle(ph.green).fillRect(11,8,3,2).fillRect(17,8,3,2)});
 tex("leader",34,26,()=>{g.fillStyle(0x381451).fillTriangle(17,12,0,1,7,23).fillTriangle(17,12,34,1,27,23);g.lineStyle(2,ph.gold).strokeTriangle(17,12,1,2,7,22).strokeTriangle(17,12,33,2,27,22);g.fillStyle(0x9a3cc0).fillCircle(17,12,8);g.fillStyle(ph.green).fillRect(12,9,4,3).fillRect(19,9,4,3);g.fillStyle(ph.gold).fillTriangle(17,2,13,7,21,7)});
 tex("leaderCracked",34,26,()=>{g.fillStyle(0x381451).fillTriangle(17,12,0,1,7,23).fillTriangle(17,12,34,1,27,23);g.lineStyle(2,ph.gold).strokeTriangle(17,12,1,2,7,22).strokeTriangle(17,12,33,2,27,22);g.fillStyle(0x9a3cc0).fillCircle(17,12,8);g.fillStyle(ph.green).fillRect(12,9,4,3).fillRect(19,9,4,3);g.lineStyle(2,0xff6b62).beginPath().moveTo(18,4).lineTo(15,11).lineTo(19,15).lineTo(15,23).strokePath()});
 tex("wasp",32,28,()=>{g.fillStyle(0x4f125e).fillTriangle(16,13,0,4,7,22).fillTriangle(16,13,32,4,25,22);g.fillStyle(0x68dc76).fillEllipse(16,14,12,24);g.fillStyle(0xffd35a).fillRect(11,9,10,3).fillRect(11,16,10,3);g.fillStyle(0xff6b9b).fillCircle(13,7,2).fillCircle(19,7,2);g.fillStyle(0xf5e783).fillTriangle(16,27,12,20,20,20)});
 tex("rootCaptor",48,42,()=>{g.fillStyle(0x170d24).fillTriangle(24,4,0,19,10,37).fillTriangle(24,4,48,19,38,37);g.lineStyle(3,ph.gold).strokeTriangle(24,4,1,19,10,36).strokeTriangle(24,4,47,19,38,36);g.fillStyle(0x5d2875).fillEllipse(24,18,27,25);g.fillStyle(ph.green).fillCircle(18,16,3).fillCircle(30,16,3);g.fillStyle(0x0a2f19).fillTriangle(24,41,16,27,32,27);g.lineStyle(2,ph.green).strokeTriangle(24,40,17,27,31,27)});
 tex("borer",31,34,()=>{g.fillStyle(0xa76723).fillEllipse(15,17,24,30);g.lineStyle(3,ph.gold).strokeEllipse(15,17,24,30);g.fillStyle(0x4d183e).fillRect(13,3,4,26);g.fillStyle(ph.green).fillCircle(10,10,2).fillCircle(20,10,2)});
 tex("spore",27,29,()=>{g.fillStyle(0x78c85e).fillCircle(13,13,12);g.fillStyle(0xd9ff8a).fillCircle(9,8,3).fillCircle(18,14,2);g.fillStyle(0x9253a5).fillRect(11,22,5,7)});tex("small",12,12,()=>{g.fillStyle(0xb2ee78).fillCircle(6,6,5);g.fillStyle(0x54217a).fillCircle(5,5,2)});
 g.destroy();
}
function forest(s:Phaser.Scene){
 const back=s.add.image(240,360,"forest-back").setDisplaySize(494,741).setDepth(-6);
 const mid=s.add.image(240,360,"forest-mid").setDisplaySize(488,732).setDepth(-4).setAlpha(.2);
 const front=s.add.image(240,360,"forest-front").setDisplaySize(488,732).setDepth(7).setAlpha(.48);
 s.tweens.add({targets:back,y:355,duration:10000,yoyo:true,repeat:-1,ease:"Sine.inOut"});
 s.tweens.add({targets:mid,y:366,duration:7200,yoyo:true,repeat:-1,ease:"Sine.inOut"});
 s.tweens.add({targets:front,y:351,duration:4800,yoyo:true,repeat:-1,ease:"Sine.inOut"});
}
function leafBurst(s:Phaser.Scene,x:number,y:number,count=10){for(let i=0;i<count;i++){const p=s.add.rectangle(x,y,3+i%3,6,i%3===0?ph.gold:ph.green).setDepth(10).setAngle(i*37);s.tweens.add({targets:p,x:x+Phaser.Math.Between(-65,65),y:y+Phaser.Math.Between(-70,55),angle:i*90,alpha:0,duration:Phaser.Math.Between(280,620),onComplete:()=>p.destroy()})}}
function tone(_s:Phaser.Scene,f:number,d=.05,v=.04){if(sfxMuted)return;try{const C=window.AudioContext||(window as unknown as {webkitAudioContext:typeof AudioContext}).webkitAudioContext;audioContext??=new C();const c=audioContext;if(c.state==="suspended")void c.resume();const o=c.createOscillator(),gain=c.createGain();o.type=f<170?"sawtooth":f>600?"triangle":"square";o.frequency.setValueAtTime(f,c.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(45,f*.72),c.currentTime+d);gain.gain.setValueAtTime(v,c.currentTime);gain.gain.exponentialRampToValueAtTime(.001,c.currentTime+d);o.connect(gain).connect(c.destination);o.start();o.stop(c.currentTime+d)}catch{}}
export function createCanopyGame(parent:HTMLElement){return new Phaser.Game({type:Phaser.AUTO,width:W,height:H,parent,backgroundColor:pc.bg,pixelArt:true,roundPixels:true,physics:{default:"arcade",arcade:{gravity:{x:0,y:0},debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[BootScene,TitleScene,GameScene,GameOverScene],fps:{target:60,forceSetTimeOut:false},input:{activePointers:3}})}
